### ISSUE TITLE
Bitnami repo site returns "Access Denied"

### ISSUE THREAD

**Issue by mkesper** [bitnami/charts#13309]
### Name and Version

*

### What steps will reproduce the bug?

Open https://charts.bitnami.com/bitnami in browser.
It returns "Access Denied"

### What do you see instead?

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4551C0K8QEHDNSZF</RequestId>
<HostId>
+Fwm691GGYgS1HXJwZlXTi53MyjNazKHOvlUUHfodce77osvW7AHl4YgKUF8XMozPf3JJhhm5d8=
</HostId>
</Error>

**Comment by carrodher** [comment]
Please note this URL is not accessible using a web browser. The only accessible URL is https://charts.bitnami.com/ where a static HTLM is shown. The idea of `https://charts.bitnami.com/bitnami` is to be used with the Helm CLI

**Comment by mkesper** [comment]
Thanks for clarifying this! :)
FYI the underlying issue was an update of Nexus repo manager which ran into a limitation of the newer versions of the snakeyaml library.
[FasterXML jackson issue](https://github.com/FasterXML/jackson-dataformats-text/issues/337)
[Nexus Repomanager issue](https://issues.sonatype.org/projects/NEXUS/issues/NEXUS-35623?filter=allissues), promised to be fixed in 3.44.

**Comment by ali-idrizi** [comment]
Not sure if related, but when running `helm repo add bitnami https://charts.bitnami.com/bitnami` I am getting:

```
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com on 172.31.32.1:53: no such host
```

Both locally and on GitHub Actions.

**Comment by hmphu** [comment]
Same here

```
❯ helm repo add bitnami https://charts.bitnami.com/bitnami
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com on 8.8.4.4:53: no such host
```

**Comment by ferd** [comment]
It appears DNS config is busted or resolves to nothing usable.

```
dig charts.bitnami.com @8.8.8.8

; <<>> DiG 9.10.6 <<>> charts.bitnami.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33437
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;charts.bitnami.com.            IN      A

;; ANSWER SECTION:
charts.bitnami.com.     10209   IN      CNAME   d1xe8nqhpmcyfh.cloudfront.net.

;; AUTHORITY SECTION:
d1xe8nqhpmcyfh.cloudfront.net. 45 IN    SOA     ns-781.awsdns-33.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```

**Comment by mitchdawson1982** [comment]
Looks to be working again now

**Comment by hmphu** [comment]
Looks like it is working again on my local , but not my EKS cluster. I think we need to wait sometimes until DNS fixed

**Comment by carrodher** [comment]
Thanks for reporting this issue. It was a problem in the CloudFront distribution that we used for the Charts repository.

The problem is that terraform recreated the CloudFront collection, creating a new DNS endpoint that needed to replicate globally. A small number of [DNS](https://dnschecker.org/#CNAME/charts.bitnami.com) are still resolving the old CloudFront collection name, but for the most part, the issue should be fixed shortly.

**Comment by cberg-aot** [comment]
![image](https://user-images.githubusercontent.com/93226309/199558714-5d2d2407-a0e9-4fc0-8eb7-44da878d3eb2.png)
Problem persists when trying to download charts from repo.

**Comment by cberg-aot** [comment]
Problem persists.  403 Forbidden. 

![image](https://user-images.githubusercontent.com/93226309/199845435-f3066228-081d-4542-97ca-1bc1aabb26cb.png)

**Comment by cberg-aot** [comment]
PROBLEM STILL PERSISTS.  UPDATE?

**Comment by DBVEERESH765** [comment]
Problem still persists, any comments please?

helm repo add bitnami https://charts.bitnami.com/bitnami
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml":

**Comment by vvp1983** [comment]
Problem still persist

**Comment by carrodher** [comment]
It seems there are issues with CloudFlare, which is used under the hood to serve the charts; see https://github.com/bitnami/charts/issues/31257.

That said, just so you know, this method of consuming Bitnami Helm charts is neither the default nor the recommended approach. We strongly encourage consuming Bitnami Helm charts as OCI artifacts. For more information, please refer to https://github.com/bitnami/charts/issues/30110.
