### ISSUE TITLE
[bitnami/postgresql] Not able to pull chart auth error

### ISSUE THREAD

**Issue by apgapg** [bitnami/charts#20314]
### Name and Version

postgresql 13.1.5

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the following command to install chart

```
helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql
```

It show following error:

```
Error: GET "https://registry-1.docker.io/v2/bitnamicharts/postgresql/tags/list": unable to retrieve credentials
```

### What is the expected behavior?

Chart should get install without auth error

### What do you see instead?

Error: GET "https://registry-1.docker.io/v2/bitnamicharts/postgresql/tags/list": unable to retrieve credentials

**Comment by javsalgar** [comment]
Hi,

Could you try with the latest version of helm? This is related to an upstream issue solved in the latest version of the client.

**Comment by fbyrne** [comment]
Hi, could you link to the client issue causing this please.
Im running into the same issue running v3.13.1
thx

**Comment by javsalgar** [comment]
https://github.com/helm/helm/issues/12423

**Comment by adamency** [comment]
@javsalgar This is wrong. This is still an issue on Helm 3.16.3:

```
$ helm version
version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"dirty", GoVersion:"go1.23.3"}
$ helm template -n identity keycloak oci://registry-1.docker.io/bitnamicharts/keycloak -f values.yaml
Error: GET "https://registry-1.docker.io/v2/bitnamicharts/keycloak/tags/list": unable to retrieve credentials
```

**Comment by adamency** [comment]
## PSA for MacOS users

**If you get this error appearing for any OCI registry today, it is most likely related to https://github.com/docker/for-mac/issues/7520.**

You can solve it by doing this: https://github.com/docker/for-mac/issues/7520#issuecomment-2593247448
