### ISSUE TITLE
[grafana] missing existingSecret option for GF_SECURITY_ADMIN_PASSWORD 

### ISSUE THREAD

**Issue by alex1989hu** [bitnami/charts#2052]
**Which chart**:

grafana (1.2.12)

**Description**

Not able to define already existingSecret for `GF_SECURITY_ADMIN_PASSWORD`. For instance, it does not allow us to use *sealed-secrets* to encrypt admin password.

A working example can be found here: [stable/grafana](https://github.com/helm/charts/blob/1a10889120c1abae1b03f252855552287fc3aa1c/stable/grafana/values.yaml#L230-L233), but this is also implemented in the actual bitnami/grafana chart for `smtp`.

**Steps to reproduce the issue:**

N/A

**Describe the results you received:**

N/A

**Describe the results you expected:**
Possibility to define already existing secret to set Grafana's admin user password as it is currently available for `smtp`.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by juan131** [comment]
Thanks for this great suggestion @alex1989hu !!
I just created a PR to address it

**Comment by juan131** [comment]
Hi @alex1989hu 

We just merged the changes and they are available in the latest version (**1.3.0**) of the Bitnami Grafana chart. Thanks again for the suggestion!

**Comment by alex1989hu** [comment]
> Hi @alex1989hu
> 
> We just merged the changes and they are available in the latest version (**1.3.0**) of the Bitnami Grafana chart. Thanks again for the suggestion!

I really appreciate your work @juan131 . Once it has been published, I will deploy and test

**Comment by juan131** [comment]
You're welcome @alex1989hu 

Please let us know about your results once you test it!

**Comment by alex1989hu** [comment]
Unfortunately the [chart](https://charts.bitnami.com/bitnami/index.yaml) is still not published: `created: "2020-03-11T23:46:56.807189675Z"`

**Comment by juan131** [comment]
My fault! I thought I had triggered the process to update the chart index but I did not! Now it's ready:

```
$ helm repo update && helm search repo bitnami/grafana
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/grafana	1.3.3        	6.6.2      	Grafana is an open source, feature rich metrics...
```
