### ISSUE TITLE
[bitnami/mongodb] Cannot use with replicaSet enabled and usePassword=false

### ISSUE THREAD

**Issue by ushakov** [bitnami/charts#2075]
(Moved from helm/charts#21216)

**Describe the bug**

I start mongodb with replica set enabled by running

```
helm install mongodb-prod stable/mongodb --set usePassword=false,replicaSet.enabled=true
```

The cluster does not become available.

**Version of Helm and Kubernetes**:

```
$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/mongodb

**What happened**:

Primary does not start:

```

[38;5;6m [38;5;5m13:13:41.29 [0m
[38;5;6m [38;5;5m13:13:41.30 [0m[1mWelcome to the Bitnami mongodb container[0m
[38;5;6m [38;5;5m13:13:41.30 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m
[38;5;6m [38;5;5m13:13:41.30 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m
[38;5;6m [38;5;5m13:13:41.30 [0mSend us your feedback at [1mcontainers@bitnami.com[0m
[38;5;6m [38;5;5m13:13:41.30 [0m
[38;5;6m [38;5;5m13:13:41.30 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **
[38;5;6m [38;5;5m13:13:41.32 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...
[38;5;6m [38;5;5m13:13:41.32 [0m[38;5;1mERROR[0m ==> The MONGODB_ROOT_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is only recommended
```

Arbiter does not start:

```
[38;5;6m [38;5;5m13:13:46.95 [0m
[38;5;6m [38;5;5m13:13:46.95 [0m[1mWelcome to the Bitnami mongodb container[0m
[38;5;6m [38;5;5m13:13:46.95 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m
[38;5;6m [38;5;5m13:13:46.96 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m
[38;5;6m [38;5;5m13:13:46.96 [0mSend us your feedback at [1mcontainers@bitnami.com[0m
[38;5;6m [38;5;5m13:13:46.96 [0m
[38;5;6m [38;5;5m13:13:46.96 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **
[38;5;6m [38;5;5m13:13:46.97 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...
[38;5;6m [38;5;5m13:13:46.98 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...
[38;5;6m [38;5;5m13:13:46.98 [0m[38;5;2mINFO [0m ==> No injected configuration files found. Creating default config files...
[38;5;6m [38;5;5m13:13:46.99 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...
[38;5;6m [38;5;5m13:13:47.86 [0m[38;5;2mINFO [0m ==> Creating users...
[38;5;6m [38;5;5m13:13:47.86 [0m[38;5;2mINFO [0m ==> Users created
[38;5;6m [38;5;5m13:13:47.87 [0m[38;5;2mINFO [0m ==> Configuring MongoDB replica set...
[38;5;6m [38;5;5m13:13:47.88 [0m[38;5;2mINFO [0m ==> Stopping MongoDB...
/libmongodb.sh: line 793: 4: password is required
[38;5;6m [38;5;5m13:13:50.13 [0m[38;5;2mINFO [0m ==> Stopping M
```

**What you expected to happen**:

Mongodb starts and is available :)

**How to reproduce it** (as minimally and precisely as possible):

I believe an empty k8s cluster would be ok for reproducing this.

**Anything else we need to know**:

The cluster is managed by kops on AWS

**Comment by hammady** [comment]
I am facing the same exact issue. I am able to edit the primary template and add that environment variable but the arbiter still gives the same error. Did you get around that?

**Comment by ushakov** [comment]
Nope. I also set the ALLOW_EMPTY_PASSWORD environment variabel to "yes" and still arbiter fails with an error.

**Comment by dani8art** [comment]
Hi @ushakov, I wanted to give you an update about this, I was trying some approaches to fix that issue taking into account other cases that could happen. As it is an issue related to the container logic we need to be careful about the solutions side effects. Were are thinking about making root password optional when `$ALLOW_EMPTY_PASSWORD` is set so that the issue should be fixed but there is a question here, Could mongodb client connects to a replicaset without password?

**Comment by laloyalo** [comment]
Sorry to write down in a closed issue, but even with #2091 I am still facing this issue. The arbiter can not connect to the primary, although the primary seems to be running and configured, nor can the secondary connect to it. It seems to me that even with `ALLOW_EMPTY_PASSWORD=yes`, MongoDB expects a key to sync the replicas, otherwise the arbiter marks this as:

```bash
mongodb 06:19:56.96 INFO ==> Found MongoDB server listening at mongodb:27017 !
mongodb 06:22:55.60 ERROR ==> Node mongodb did not become available
mongodb 06:22:55.64 INFO ==> Stopping MongoDB...
```
So not sure how to proceed, should this be handled in a new issue. It seems like this is a good one, because the actual combination of parameters to cause this to fail is:

1. `replicaSet.enabled = true`
2. `usePassword = false`

I am not too well versed in the internals of MongoDB 4.2, so the above are mostly guesses about a Key. I have a working with `replicaSet.enabled=false`.

Chart version: ` 7.13.0`
MongoDB image: `docker.io/bitnami/mongodb:4.2.6-debian-10-r13`

I also checked for non deleted volumes, but also with a new deployment this is happening.

Please let me know if I can provide more info on this.

Thanks!

**Comment by dani8art** [comment]
Hi @laloyalo , thank you for your feedback, I double-checked the issue and yes you are right, we are still not able to set a deployment with those values. I'm going to re-open the issue so we can investigate a bit more about this problem and try to solve it. Could you provide any other info about your deployment that could help?

**Comment by emrahcetiner** [comment]
@dani8art, could be written in the readme file this chart does not work without a password until fixing the issue.

**Comment by dani8art** [comment]
Hi @emrahcetiner we are going to try fixing it before adding this kind of notice to the `README.md` it is a feature that we want to support. We have opened an internal task in order to evaluate it and figure out what is happening. Unfortunately, we can not give you an ETA but we keep you updated about the status of the issue. Thank you so much for the feedback.

**Comment by laloyalo** [comment]
Hi @dani8art, thank you for the quick response. The deployment was attempted in GKE with K8s version `1.15.11-gke.9`. I have a weird combination of helm. Since I am using Rancher2, it manages its own distribution of helm, which currently is: `v2.10+unreleased`, but I installed tiller on its own, which gives version: `v2.16.3`. I can try a deployment with Helm v3 if that is of any use, which I also remember doing back before #2091 was merged, which did not work because of the missing `ALLOW_EMPTY_PASSWORD=yes` and missing modifications to the bitnami image.
Please let me know if you'd like me to try out that or if any other information may help.

**Comment by dani8art** [comment]
Hi @laloyalo , Yes we did some effort on those PRs, and the container in the PR was also updated but without success. That would be good if you a chance to try and investigate a bit, even if you want to propose something in a PR we will be happy to handle and review it. Thank you so much!

**Comment by joancafom** [comment]
Hey! 

Some great updates regarding this issue. We have recently released a new version of the [bitnami-docker-mongodb](https://github.com/bitnami/bitnami-docker-mongodb/commit/9e20f75542a8791b193835a5934d52121cc70fae) container with changes that should fix the problem. Chart was also [updated](https://github.com/bitnami/charts/commit/83e99f9c7728e0377929fb0800eeffd2759aa0f7) so as to use this last image version.

Thanks everyone so much for your feedback!

**Comment by laloyalo** [comment]
Thank you @joancafom , I will do a test on Monday and get back so that we can close this as soon as possible.
