### ISSUE TITLE
[bitnami/wordpress] Ingress exposes internal 8080 port when trying to access /wp-admin (only without trailing slash)

### ISSUE THREAD

**Issue by rgrebski** [bitnami/charts#2111]
**Which chart**:
wordpress-9.0.4

**Description**
I have just installed wordpress chart on GKE, exposed with http and https.
When I try opening http(s)://my-url/wp-admin (no trailing slash) I get:

> → curl https://my-url/wp-admin
> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
>     <title>301 Moved Permanently</title>
> </head><body>
> <h1>Moved Permanently</h1>
> <p>The document has moved <a href="http://my-url:8080/wp-admin/">here</a>.</p>
> </body></html>

However if I add trailing slash everything works ok

**Steps to reproduce the issue:**

1. Install chart with following values.yaml:
```
service:
  type: LoadBalancer
persistence:
  enabled: false
```
2. Once it is deployed try opening /wp-admin

**Describe the results you received:**

301 response with trailing slash to "/wp-admin/" with port 8080 instead of 80

**Describe the results you expected:**

301 response with trailing slash to port 80 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-gke.3", GitCommit:"2ccf2c797713077f4a3d0f87c4b4bae725362326", GitTreeState:"clean", BuildDate:"2020-01-29T19:27:22Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by dani8art** [comment]
Hi @rgrebski, thank you for reporting this issue, it is reproducible not only in GKE also in other environments when `LoadBalancer` is used. You can try other URLs like
- http://my-url/wp-admin/
- http://my-url/wp-admin/index.php
- http://my-url/admin

All of them are working fine, it seems there is a wrong redirection somewhere when going `/wp-admin` and we need to find it.

**Comment by rgrebski** [comment]
Thanks for the update, please note that I observe the same when using nginx-ingress + NodePort.
I took a quick look at nginx config and it seems fine, my guess is that its either apache or wordpress config issue. I will do some more "debugging" over the weekend

**Comment by dani8art** [comment]
I did some tests from the container so I could realize apache is doing the redirection for `/wp-admin` while Wordpress is doing the others. If you go inside the container
```
$ kubectl exec -ti w-wordpress-7b689fb64b-qrg9j bash
```
You could execute 
```
$ curl -v http://localhost:8080/wp-admin
> GET /wp-admin HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 25 Mar 2020 07:57:09 GMT
< Server: Apache/2.4.41 (Unix) OpenSSL/1.1.1d PHP/7.4.3
< Location: http://localhost:8080/wp-admin/
< Content-Length: 239
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost:8080/wp-admin/">here</a>.</p>
</body></html>
```
then if you do
```
$ curl -v http://localhost:8080/admin 
> GET /admin HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Wed, 25 Mar 2020 07:59:10 GMT
< Server: Apache/2.4.41 (Unix) OpenSSL/1.1.1d PHP/7.4.3
< X-Powered-By: PHP/7.4.3
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <http://localhost:8080/wp-json/>; rel="https://api.w.org/"
< X-Redirect-By: WordPress
< Location: http://localhost:8080/wp-admin/
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
```
then we could see three main differences
- HTTP redirect codes are difference `/wp-admin` -> `301` `/admin` -> `302`
- Body `/wp-admin` has body
- `/admin` has a header `X-Redirect-By: WordPress`

The thing is that k8s service which is doing the proxy between pods is not interpreting the first redirection well if you try
```
$ curl -v http://<service_ip>/wp-admin
## redirect to http://<service_ip>:8080/wp-admin/
```
however, if you do
```
$ curl -v http://<service_ip>/admin
## redirect to http://<service_ip>/wp-admin/
```

**Comment by dani8art** [comment]
Hi @rgrebski any updates on that? did you try something more? were you able to solve the problems?

**Comment by rgrebski** [comment]
@dani8art I have been quite busyrecently, I will handle the issue this weekend

**Comment by dani8art** [comment]
Ok good, let's keep in touch! thx

**Comment by rgrebski** [comment]
The easiest thing I can think of is adding ingress annotation that will do redirect by itself:
`    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /wp-admin$ {
           return 301 /wp-admin/;
       }
`

**Comment by marcosbc** [comment]
Thanks for sharing the solution! We're glad you were able to fix this.

We have found similar issues in a past support case, i.e. [with phpMyAdmin](https://community.bitnami.com/t/unable-to-connect-to-phpmyadmin-bitnami-wordpress-nginx-ssl/79277/4) (accessing from /phpmyadmin/ works but not /phpmyadmin) and it looks related to some NGINX configuration.

However, we've not yet identified the issue. We've associated an internal task with this issue, with the hope of being able to get back and let you know what the issue on the other case was.

**Comment by v-six** [comment]
Thank you @rgrebski for the workaround, it really helped !
Any update about the "long term" resolution @marcosbc ?

**Comment by dani8art** [comment]
Hi @v-six , unfortunately we can not give you an ETA and we've not yet identified the root cause for this issue. We would try to identify, however, if you guys have a chance and would like to contribute to the `bitnami/wordpress` and `bitnami/bitnami-docker-wordpress`, we will be happy to handle the PRs. Thank you so much for your feedback!

**Comment by marcosbc** [comment]
Hi, it seems this behavior is happening because of the NGINX `absolute_redirect` configuration: http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect

Setting the following configuration to your NGINX server should fix the issue:

```
absolute_redirect off;
```

**Comment by bilaltas** [comment]
+1

**Comment by dani8art** [comment]
I'm sorry but the task is still in our backlog, we can't provide an ETA for the fix

**Comment by dani8art** [comment]
Hi it seems this error is fixed as commented in https://github.com/bitnami/charts/issues/2111#issuecomment-653546313, did you faced it after applying this fix.

**Comment by bilaltas** [comment]
I think it should be applied on the build itself since it's always necessary to prevent being redirected to the internal port. It's not good practice for WP image users to apply that configuration every time. Right?

**Comment by dani8art** [comment]
We think so as well, we have a task to apply it, unfortunately we can not give you an ETA, however, we are open to contributions if you have a chance and would like to contribute to the bitnami/wordpress and bitnami/bitnami-docker-wordpress, we will be happy to handle the PRs. Thank you so much for your feedback!

**Comment by lukasmrtvy** [comment]
@dani8art any progress? thanks

**Comment by marcosbc** [comment]
Hi @lukasmrtvy, we have unfortunately not fixed this issue yet. However, in the meantime, you may be able to solve this on your side in the meantime by mounting a file to `/opt/bitnami/nginx/conf/server_blocks` with the contents `absolute_redirect off;`.

**Comment by cbirkenbeul** [comment]
This does not happen just for NGINX.
I've setup a k3s env with traefik as reverse proxy. There is the same behavior.

**Comment by marcosbc** [comment]
You are right @cbirkenbeul, I should clarify that this is an issue that happens both with NGINX and the Apache web servers, when they are not able to detect the hostname used to access the application (since this is proxied via the reverse proxies).

**Comment by radoslav-stefanov** [comment]
I am experiencing this as well. Using the Apache image with CloudFlare Argo tunnel as ingress.

The main problem I have it is exposing the 8080 port, which can lead to double indexing.

**Comment by marcosbc** [comment]
@radoslav-stefanov Unfortunately we have not been able to identify a fix yet, as it affects any folder that is being accessed without a trailing slash (`/`). For Apache, you can read more about the redirection [here](http://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryslash).

If you have any ideas, feel free to share them. In the meantime, the recommendation is to access all folders with a trailing slash (`/`).

**Comment by varac** [comment]
The same happens for me when using the nginx chart alone (to deploy a static website i.e.). Is there an issue for the nginx chart already that tracks this or should this issue maybe renamed to indicate this is not just a problem with the wordpress chart ?

**Comment by juan131** [comment]
Hi @varac 

Please open a different issue to report the issue with NGINX, let's keep this issue exclusive for WordPress since the web servers used in the images are different and a possible solution for this WordPress might not work for NGINX.

**Comment by fmulero** [comment]
Hi, we recently released a new version of the bitnami/wordpress container (`bitnami/wordpress:5.8.3-debian-10-r17`) with a fix for this issue
