### ISSUE TITLE
[bitnami/kafka] Can not mount existing PVs  

### ISSUE THREAD

**Issue by hahahannes** [bitnami/charts#24479]
### Name and Version

kafka/27.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

- [ ] Create two PersistentVolumeClaims `data-0` and `data-1` 
In my specific case, the PVCs were created during an older deployment of kafka as part of the Statefulset Configuration of the broker with two replicas.
```yaml
      kind: PersistentVolumeClaim
      metadata:
        name: data-0
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```

- [ ] `helm install ...` 

The main point is to set broker.persistence.existingClaim = "data".
The setup is a zookeeper mode Deployment with 2 brokers.

### Are you using any custom parameters or values?

```yaml
broker:
  ## @param broker.replicaCount Number of Kafka broker-only nodes
  ##
  replicaCount: 2
  ## @param broker.minId Minimal node.id values for broker-only nodes. Do not change after first initialization.
  ## Broker-only id increment their ID starting at this minimal value.
  ## We recommend setting this this value high enough, as IDs under this value will be used by controller-eligible nodes
  ##
  ##
  minId: 100
  ## @param broker.zookeeperMigrationMode Set to true to deploy cluster controller quorum
  ## This allows configuring both kraft and zookeeper modes simultaneously in order to perform the migration of the Kafka metadata.
  ## Ref. https://docs.confluent.io/platform/current/installation/migrate-zk-kraft.html
  ##
  zookeeperMigrationMode: false
  ## @param broker.config Configuration file for Kafka broker-only nodes, rendered as a template. Auto-generated based on chart values when not specified.
  ## @param broker.existingConfigmap ConfigMap with Kafka Configuration for broker-only nodes.
  ## NOTE: This will override the configuration based on values, please act carefully
  ## If both are set, the existingConfigMap will be used.
  ##
  config: ""
  existingConfigmap: ""
  ## @param broker.extraConfig Additional configuration to be appended at the end of the generated Kafka broker-only nodes configuration file.
  ##
  extraConfig: ""
  ## @param broker.secretConfig Additional configuration to be appended at the end of the generated Kafka broker-only nodes configuration file.
  ## This value will be stored in a secret.
  ##
  secretConfig: ""
  ## @param broker.existingSecretConfig Secret with additonal configuration that will be appended to the end of the generated Kafka broker-only nodes configuration file
  ## The key for the configuration should be: server-secret.properties
  ## NOTE: This will override broker.secretConfig value
  ##
  existingSecretConfig: ""
  ## @param broker.heapOpts Kafka Java Heap size for broker-only nodes
  ##
  heapOpts: -Xmx1024m -Xms1024m
  ## @param broker.command Override Kafka container command
  ##
  command: []
  ## @param broker.args Override Kafka container arguments
  ##
  args: []
  ## @param broker.extraEnvVars Extra environment variables to add to Kafka pods
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/kafka#configuration
  ## e.g:
  ## extraEnvVars:
  ##   - name: KAFKA_CFG_BACKGROUND_THREADS
  ##     value: "10"
  ##
  extraEnvVars: []
  ## @param broker.extraEnvVarsCM ConfigMap with extra environment variables
  ##
  extraEnvVarsCM: ""
  ## @param broker.extraEnvVarsSecret Secret with extra environment variables
  ##
  extraEnvVarsSecret: ""
  ## @param broker.extraContainerPorts Kafka broker-only extra containerPorts.
  ##
  extraContainerPorts: []
  ## Configure extra options for Kafka containers' liveness, readiness and startup probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  ## @param broker.livenessProbe.enabled Enable livenessProbe on Kafka containers
  ## @param broker.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param broker.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param broker.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param broker.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param broker.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  ## @param broker.readinessProbe.enabled Enable readinessProbe on Kafka containers
  ## @param broker.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param broker.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param broker.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param broker.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param broker.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    failureThreshold: 6
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
  ## @param broker.startupProbe.enabled Enable startupProbe on Kafka containers
  ## @param broker.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ## @param broker.startupProbe.periodSeconds Period seconds for startupProbe
  ## @param broker.startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ## @param broker.startupProbe.failureThreshold Failure threshold for startupProbe
  ## @param broker.startupProbe.successThreshold Success threshold for startupProbe
  ##
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  ## @param broker.customLivenessProbe Custom livenessProbe that overrides the default one
  ##
  customLivenessProbe: {}
  ## @param broker.customReadinessProbe Custom readinessProbe that overrides the default one
  ##
  customReadinessProbe: {}
  ## @param broker.customStartupProbe Custom startupProbe that overrides the default one
  ##
  customStartupProbe: {}
  ## @param broker.lifecycleHooks lifecycleHooks for the Kafka container to automate configuration before or after startup
  ##
  lifecycleHooks: {}
  ## Kafka init container resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param broker.initContainerResources.limits The resources limits for the container
  ## @param broker.initContainerResources.requests The requested resources for the container
  ##
  initContainerResources:
    limits: {}
    requests: {}
  ## Kafka resource requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param broker.resources.limits The resources limits for the container
  ## @param broker.resources.requests The requested resources for the container
  ##
  resources:
    limits: {}
    requests: {}
  ## Kafka pods' Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param broker.podSecurityContext.enabled Enable security context for the pods
  ## @param broker.podSecurityContext.fsGroup Set Kafka pod's Security Context fsGroup
  ## @param broker.podSecurityContext.seccompProfile.type Set Kafka pod's Security Context seccomp profile
  ##
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    seccompProfile:
      type: "RuntimeDefault"
  ## Kafka containers' Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param broker.containerSecurityContext.enabled Enable Kafka containers' Security Context
  ## @param broker.containerSecurityContext.runAsUser Set Kafka containers' Security Context runAsUser
  ## @param broker.containerSecurityContext.runAsNonRoot Set Kafka containers' Security Context runAsNonRoot
  ## @param broker.containerSecurityContext.allowPrivilegeEscalation Force the child process to be run as non-privileged
  ## @param broker.containerSecurityContext.readOnlyRootFilesystem Allows the pod to mount the RootFS as ReadOnly only
  ## @param broker.containerSecurityContext.capabilities.drop Set Kafka containers' server Security Context capabilities to be dropped
  ## e.g:
  ##   containerSecurityContext:
  ##     enabled: true
  ##     capabilities:
  ##       drop: ["NET_RAW"]
  ##     readOnlyRootFilesystem: true
  ##
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
  ## @param broker.hostAliases Kafka pods host aliases
  ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
  ##
  hostAliases: []
  ## @param broker.hostNetwork Specify if host network should be enabled for Kafka pods
  ##
  hostNetwork: false
  ## @param broker.hostIPC Specify if host IPC should be enabled for Kafka pods
  ##
  hostIPC: false
  ## @param broker.podLabels Extra labels for Kafka pods
  ## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  ##
  podLabels: {}
  ## @param broker.podAnnotations Extra annotations for Kafka pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: {}
  ## @param broker.podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAffinityPreset: ""
  ## @param broker.podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ##
  podAntiAffinityPreset: soft
  ## Node affinity preset
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
  ##
  nodeAffinityPreset:
    ## @param broker.nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
    ##
    type: ""
    ## @param broker.nodeAffinityPreset.key Node label key to match Ignored if `affinity` is set.
    ## E.g.
    ## key: "kubernetes.io/e2e-az-name"
    ##
    key: ""
    ## @param broker.nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set.
    ## E.g.
    ## values:
    ##   - e2e-az1
    ##   - e2e-az2
    ##
    values: []
  ## @param broker.affinity Affinity for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
  ##
  affinity: {}
  ## @param broker.nodeSelector Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  ## @param broker.tolerations Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param broker.topologySpreadConstraints Topology Spread Constraints for pod assignment spread across your cluster among failure-domains. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#spread-constraints-for-pods
  ##
  topologySpreadConstraints: []
  ## @param broker.terminationGracePeriodSeconds Seconds the pod needs to gracefully terminate
  ## ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution
  ##
  terminationGracePeriodSeconds: ""
  ## @param broker.podManagementPolicy StatefulSet controller supports relax its ordering guarantees while preserving its uniqueness and identity guarantees. There are two valid pod management policies: OrderedReady and Parallel
  ## ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ##
  podManagementPolicy: Parallel
  ## @param broker.minReadySeconds How many seconds a pod needs to be ready before killing the next, during update
  ##
  minReadySeconds: 0
  ## @param broker.priorityClassName Name of the existing priority class to be used by kafka pods
  ## Ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
  ##
  priorityClassName: ""
  ## @param broker.runtimeClassName Name of the runtime class to be used by pod(s)
  ## ref: https://kubernetes.io/docs/concepts/containers/runtime-class/
  ##
  runtimeClassName: ""
  ## @param broker.enableServiceLinks Whether information about services should be injected into pod's environment variable
  ## The environment variables injected by service links are not used, but can lead to slow kafka boot times or slow running of the scripts when there are many services in the current namespace.
  ## If you experience slow pod startups or slow running of the scripts you probably want to set this to `false`.
  ##
  enableServiceLinks: true
  ## @param broker.schedulerName Name of the k8s scheduler (other than default)
  ## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
  ##
  schedulerName: ""
  ## @param broker.updateStrategy.type Kafka statefulset strategy type
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  ##
  updateStrategy:
    type: RollingUpdate
  ## @param broker.extraVolumes Optionally specify extra list of additional volumes for the Kafka pod(s)
  ## e.g:
  ## extraVolumes:
  ##   - name: kafka-jaas
  ##     secret:
  ##       secretName: kafka-jaas
  ##
  extraVolumes: []
  ## @param broker.extraVolumeMounts Optionally specify extra list of additional volumeMounts for the Kafka container(s)
  ## extraVolumeMounts:
  ##   - name: kafka-jaas
  ##     mountPath: /bitnami/kafka/config/kafka_jaas.conf
  ##     subPath: kafka_jaas.conf
  ##
  extraVolumeMounts: []
  ## @param broker.sidecars Add additional sidecar containers to the Kafka pod(s)
  ## e.g:
  ## sidecars:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  sidecars: []
  ## @param broker.initContainers Add additional Add init containers to the Kafka pod(s)
  ## e.g:
  ## initContainers:
  ##   - name: your-image-name
  ##     image: your-image
  ##     imagePullPolicy: Always
  ##     ports:
  ##       - name: portname
  ##         containerPort: 1234
  ##
  initContainers: []
  ## Kafka Pod Disruption Budget
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  ## @param broker.pdb.create Deploy a pdb object for the Kafka pod
  ## @param broker.pdb.minAvailable Maximum number/percentage of unavailable Kafka replicas
  ## @param broker.pdb.maxUnavailable Maximum number/percentage of unavailable Kafka replicas
  ##
  pdb:
    create: false
    minAvailable: ""
    maxUnavailable: 1
  ## Enable persistence using Persistent Volume Claims
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## @param broker.persistence.enabled Enable Kafka data persistence using PVC, note that ZooKeeper persistence is unaffected
    ##
    enabled: true
    ## @param broker.persistence.existingClaim A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    ## The value is evaluated as a template
    ##
    existingClaim: ""
    ## @param broker.persistence.storageClass PVC Storage Class for Kafka data volume
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    storageClass: ""
    ## @param broker.persistence.accessModes Persistent Volume Access Modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param broker.persistence.size PVC Storage Request for Kafka data volume
    ##
    size: 10Gi
    ## @param broker.persistence.annotations Annotations for the PVC
    ##
    annotations: {}
    ## @param broker.persistence.labels Labels for the PVC
    ##
    labels: {}
    ## @param broker.persistence.selector Selector to match an existing Persistent Volume for Kafka data PVC. If set, the PVC can't have a PV dynamically provisioned for it
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}
    ## @param broker.persistence.mountPath Mount path of the Kafka data volume
    ##
    mountPath: /bitnami/kafka
  ## Log Persistence parameters
  ##
  logPersistence:
    ## @param broker.logPersistence.enabled Enable Kafka logs persistence using PVC, note that ZooKeeper persistence is unaffected
    ##
    enabled: false
    ## @param broker.logPersistence.existingClaim A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    ## The value is evaluated as a template
    ##
    existingClaim: ""
    ## @param broker.logPersistence.storageClass PVC Storage Class for Kafka logs volume
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    storageClass: ""
    ## @param broker.logPersistence.accessModes Persistent Volume Access Modes
    ##
    accessModes:
      - ReadWriteOnce
    ## @param broker.logPersistence.size PVC Storage Request for Kafka logs volume
    ##
    size: 8Gi
    ## @param broker.logPersistence.annotations Annotations for the PVC
    ##
    annotations: {}
    ## @param broker.logPersistence.selector Selector to match an existing Persistent Volume for Kafka log data PVC. If set, the PVC can't have a PV dynamically provisioned for it
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}
    ## @param broker.logPersistence.mountPath Mount path of the Kafka logs volume
    ##
    mountPath: /opt/bitnami/kafka/logs

```

### What is the expected behavior?

I expect that the correct PVC is assigned to each replica of the statefulset.

### What do you see instead?

Kubernetes reports that for each pod the PVC `data` is not found.  

### Additional information

I guess this is caused by using the `persistentVolumeClaim` field under `volumes` (e.g. https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/broker/statefulset.yaml#L438) when `existingClaim` is used in the chart values. This option seems to generate "static" PVCs names like `data` and not follow the naming convention for PVCs of statefulset. 
Instead I tried to change the chart template directly  and to use the `volumeClaimTemplates`, hoping that this would reuse existing PVCs.

**Comment by Mauraza** [comment]
Hi @hahahannes,

The `persistence.existingClaim` only mounts one PVC, which is why data appears. Did you try to use `data-0`?

**Comment by hahahannes** [comment]
Hi @Mauraza, thank you very much for your fast help!
When I have more than one replica, wouldn`t this lead to PVC `data-0` being assigned to all replicas ?

**Comment by Mauraza** [comment]
Hi @hahahannes,

Do you want the replicas connected to differents PVCs?

**Comment by hahahannes** [comment]
Maybe a solution could be to remove the `persistentVolumeClaim` in https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/broker/statefulset.yaml#L438 and only use the `volumeClaimTemplates`  in https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/broker/statefulset.yaml#L449. If I understand it correctly, this should also reuse existing PVCs.

**Comment by Mauraza** [comment]
Sorry,  I don't understand why you want to have a different PVC. Do not want to share information?
Normally the statefulset shares the same PVC, as you can see in the chart.

**Comment by hahahannes** [comment]
@Mauraza Maybe I misunderstand the kafka deployment! I thought that each broker has its own PV (and therefore three different PVCs).

**Comment by iamigui** [comment]
Hi @hahahannes , as I can see in the deployment, it creates 3 PVs and 3 PVCs (depending on your replicas), you are correct. I have deployed a single PVC and PV for 3 brokers and another PVC and PV for 3 controllers and it doesn't work at all.

I believe that by modifying the chart and creating the PVs in the statefulset and associating them to the PVCs could be a solution...

**Comment by hahahannes** [comment]
Hi @migruiz4,

my proposed solution to remove the `persistentVolumeClaim` and to only use `volumeClaimTemplates` in the statefulset.yaml template works (at least with my setup). Though, I had to change the name of the statefulset and the PVC inside the templates to generate name that matches my existing volumes.

**Comment by hahahannes** [comment]
I guess this would be too cumbersome to make the names configurable in the values.yaml  but I wanted to note here for others.

**Comment by migruiz4** [comment]
Hi @hahahannes,

I'm sorry for the late response.

Because this issue has already had a lot of discussion, I will try to explain this situation as clear as I can, so please correct me if I misunderstood anything.

Your goal is to mount two existing PVCs into the Kafka broker statefulset, so each replica uses its corresponding PVC.

This is only possible for single replica deployment or several replicas deployments sharing a single PVC, which is provided using the `existingClaim` value.

To achieve your goal, you need to mount the existing PVs (not PVCs), using the `volumeClaimTemplates`. Because of how `volumeClaimTemplates` works, each pod will create a PVC using the PV named `PVC_TEMPLATE_NAME-STATEFULSET_NAME-REPLICA_INDEX`.

You could also use `persistence.selector` to set `statefulset.spec.volumeClaimTemplates.spec.selector` (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector)

So, the main two problems I see here are:
- Attempting to mount PVCs instead of PVs.
- Misunderstanding of the usage of `persistence.existingClaim`.

In case it helps, I would recommend checking this document: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd

**Comment by migruiz4** [comment]
Reading the thread again from the beginning, it is still not clear to me whether the issue is mounting the PVCs or not being able to reuse the existing PVs because they are already attached to the PVCs of a previously existing deployment.

If your goal is to reuse the PVs without the data being reclaimed by Kubernetes when deleting the PVCs, I wrote [this](https://github.com/bitnami/charts/tree/main/bitnami/kafka#retaining-persistentvolumes). 

Although it is aimed to rename PVCs from 23.x.x to 24.x.x naming conventions, the same script may be used to rename your PVs and detach them from the existing PVCs.

**Comment by hahahannes** [comment]
Hi @migruiz4, thank you very much for your help! Your summary is correct. 

> Reading the thread again from the beginning, it is still not clear to me whether the issue is mounting the PVCs or not being able to reuse the existing PVs because they are already attached to the PVCs of a previously existing deployment.

I am not able to reuse my existing PVs. I actually forgot the possibility to rename the PVs and bound them to the new PVCs. Thanks for that!

> Misunderstanding of the usage of persistence.existingClaim

Yes, I think this was my main problem. I did not know that `existingClaim` is for single replica deployment or several replicas deployments sharing a single PVC. I thought it is a bug/missing feature that multiple PVCs are not working. I also did not know that having a shared PVC across brokers is a use case. Thats why I suggested to only use `volumeClaimTemplates` instead of `persistentVolumeClaim.claimName`. But now I see why this is used!

> To achieve your goal, you need to mount the existing PVs (not PVCs), using the volumeClaimTemplates

This is how I solved it in the end. But it required changes in the chart template files. Therefor, I created the issue to discuss possible solutions.

> You could also use persistence.selector to set statefulset.spec.volumeClaimTemplates.spec.selector
I think this might be the best solution, thanks! So I would set the reclaim policy of the PVs to retain as written in your guide and then set the selector to match them. 

Sorry for the complicated descriptions, I am still learning K8s. 
Thanks a lot!

**Comment by migruiz4** [comment]
I'm happy to help! If the issue is now clear, I will now move this issue to Closed.

Feel free to let me know if you find any further issues.

**Comment by hahahannes** [comment]
Maybe a note in the values.yaml about `existingClaim` might be helpful? I think for me it was not clear that it will be used as a constant for all replicas.

**Comment by carrodher** [comment]
> Maybe a note in the values.yaml about `existingClaim` might be helpful? I think for me it was not clear that it will be used as a constant for all replicas.

Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by GergelyMolnar** [comment]
Hi, I'm new to Helm and Kafka. 
I installed Bitnami/Kafka with K3s/Helm on a local machine for learning. I'm trying to make the data in `/bitnami/kafka` persistent so I thought a pv/pvc is the solution. I read this thread a few times, and a few others, but I can't make it work as described above. 
I have 3 controller+broker pods (default). I created a PV and PVC for this and added the name to the `controller.persistence.existingClaim` field, etc, etc. The brokers have the correct PVC assigned but they are all failing since. 
```
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-bitnami-kafka-shared
    ReadOnly:   false
```
Their status is flipping between Error and CrashLoopBackOff.
The logs are on fire and this one seems to be the culprit:
```
[2024-08-29 02:45:03,197] ERROR [BrokerServer id=2] Fatal error during broker startup. Prepare to shutdown (kafka.server.BrokerServer)
org.apache.kafka.common.KafkaException: Failed to acquire lock on file .lock in /bitnami/kafka/data. A Kafka instance in another process or thread is using this directory.
```
"existingClaim is for single replica deployment or **several replicas deployments sharing a single PVC**" I can't make it work. 

Can you help me out? What did I miss?
