### ISSUE TITLE
[bitnami/postgresql-ha] Fail to start with 'Name or service not known' error

### ISSUE THREAD

**Issue by Jaesang** [bitnami/charts#3174]
**Which chart**: postgresql-ha 3.4.3

**Describe the bug**
postgresql-0 and pgpool pod doesn't start after helm chart installed

**To Reproduce**
1. Download postgresql-ha chart and change default value.yaml from values-production.yaml
```
$ helm fetch --untar bitnami/postgresql-ha
$ cd postgresql-ha
$ cp values.yaml values.yaml.bak
$ cp values-production.yaml values.yaml
```

2. Install postgresql-ha helm chart with custom yaml.
```
helm install charts/postgresql-ha --name postgresql-ha --namespace fed -f postgresql-values.yaml
```
2. Pod status going to 'CrashLoopbackoff"
3. Log of Pod
```
$ kubectl logs -n fed postgresql-ha-postgresql-0 postgresql -f
postgresql-repmgr 09:12:39.90
postgresql-repmgr 09:12:39.90 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 09:12:39.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 09:12:39.91 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 09:12:39.91
postgresql-repmgr 09:12:39.94 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 09:12:39.97 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 09:12:39.97 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 09:12:39.98 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 09:12:40.06 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 09:12:40.07 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 09:12:40.08 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 09:12:40.21 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 09:12:40.22 INFO  ==> Initializing Repmgr...
postgresql-repmgr 09:12:40.22 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 09:12:40.23 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql-repmgr 09:12:40.24 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 09:12:40.25 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 09:12:40.29 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 09:12:40.32 INFO  ==> Configuring replication parameters
postgresql-repmgr 09:12:40.38 INFO  ==> Configuring fsync
postgresql-repmgr 09:12:40.40 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 09:12:40.41 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 09:12:40.45 INFO  ==> Starting PostgreSQL in background...
postgresql-repmgr 09:12:40.91 INFO  ==> ** Starting repmgrd **
[2020-07-21 09:12:40] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
[2020-07-21 09:12:40] [ERROR] connection to database failed
[2020-07-21 09:12:40] [DETAIL]
could not translate host name "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.fed.svc.cluster.local" to address: Name or service not known

[2020-07-21 09:12:40] [DETAIL] attempted to connect using:
  user=repmgr password=9Vg72MGKkg connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.fed.svc.cluster.local port=5432 fallback_application_
```
**Expected behavior**
postgresql pod start normally.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
$ helm version
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
This is my postgresql-values.yaml for configure
```
global:
  storageClass: rbd
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
postgresqlPassword: password
```

This is status about postgresql-ha's resources.
```
$ kubectl get all -n fed
NAME                                        READY   STATUS             RESTARTS   AGE
pod/postgresql-ha-pgpool-55b676799b-qqq64   0/1     Running            18         54m
pod/postgresql-ha-postgresql-0              1/2     CrashLoopBackOff   15         54m

NAME                                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/postgresql-ha-pgpool                ClusterIP   10.233.8.232    <none>        5432/TCP   54m
service/postgresql-ha-postgresql            ClusterIP   10.233.47.112   <none>        5432/TCP   54m
service/postgresql-ha-postgresql-headless   ClusterIP   None            <none>        5432/TCP   54m
service/postgresql-ha-postgresql-metrics    ClusterIP   10.233.62.61    <none>        9187/TCP   54m

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/postgresql-ha-pgpool   0/1     1            0           54m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/postgresql-ha-pgpool-55b676799b   1         1         0       54m

NAME                                        READY   AGE
statefulset.apps/postgresql-ha-postgresql   0/2     54m

$ kubectl get pvc -n fed
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-postgresql-ha-postgresql-0   Bound    pvc-5ccf33a1-cfdb-4b68-b9c3-efdb68c30798   20Gi       RWO            rbd            54m
```

**Comment by JorenZ** [comment]
We are seeing the same issue, incidentally since a re-deploy on our production server today as well, so about the same time as this issue perhaps. In our case, I was suspecting the fact that this cluster had run before. Perhaps there is a flag being set somewhere that leads repmgr to conclude it should have all 3 nodes up, which it does not assume on an initial deploy?
However, @Jaesang above seems to have this issue with a freshly installed postgres cluster as well...

Our symptoms seem identical:
* `postgresql-0` will not start because its repmgr instance is trying to connect to `postgresql-2` which is not up yet:
```
[...]
postgresql-repmgr 14:04:50.78 INFO  ==> ** Starting repmgrd **
[2020-07-21 14:04:52] [NOTICE] starting monitoring of node "harbor-postgres-postgresql-0" (ID: 1000)
[2020-07-21 14:04:52] [ERROR] connection to database failed
[2020-07-21 14:04:52] [DETAIL] could not translate host name "harbor-postgres-postgresql-2.harbor-postgres-postgresql-headless.harbor-postgres.svc.cluster.local" to address: Name or service not known
[2020-07-21 14:04:52] [DETAIL] attempted to connect using:
  user=repmgr password=password connect_timeout=5 dbname=repmgr host=harbor-postgres-postgresql-2.harbor-postgres-postgresql-headless.harbor-postgres.svc.cluster.local port=5432 fallback_application_name=repmgr
[2020-07-21 14:04:52] [ERROR] unable connect to upstream node (ID: 1002), terminating
[2020-07-21 14:04:52] [HINT] upstream node must be running before repmgrd can start
```
* `postgresql-1` and `postgresql-2` will not start because they're waiting for `postgresql-0` to come up
* `pgpool` in turn will not start because it has no nodes:
```
2020-07-21 14:08:33: pid 1: ERROR:  failed to make persistent db connection
2020-07-21 14:08:33: pid 1: DETAIL:  connection to host:"harbor-postgres-postgresql-0.harbor-postgres-postgresql-headless.harbor-postgres.svc.cluster.local:5432" failed
[...]
2020-07-21 14:08:33: pid 1: ERROR:  failed to make persistent db connection
2020-07-21 14:08:33: pid 1: DETAIL:  connection to host:"harbor-postgres-postgresql-1.harbor-postgres-postgresql-headless.harbor-postgres.svc.cluster.local:5432" failed
[...]
2020-07-21 14:08:33: pid 1: ERROR:  failed to make persistent db connection
2020-07-21 14:08:33: pid 1: DETAIL:  connection to host:"harbor-postgres-postgresql-2.harbor-postgres-postgresql-headless.harbor-postgres.svc.cluster.local:5432" failed
[... and so on]
```

**Comment by JorenZ** [comment]
For what it's worth: fully deleting the whole namespace and reinstalling from Helm did work just now. This was an option for us since we've barely introduced postgres in production so its database did not contain anything vital, but that sounds like a drastic measure...

I did not test which namespace contents were the culprit (pvcs? statefulset? deployment? secrets?).

**Comment by javsalgar** [comment]
Hi,

So, from what I see, it seems like a deadlock issue. @rafariossaa has been looking into that very recently, so I don't know if this is something he already experienced.

**Comment by Jaesang** [comment]
In my case, `clusterDomain` is a reason. this chart use `clusterDomain` for DB URL, if it wasn't modifed, it use `cluser.local`. But my cluster domain isn't `cluster.local`, so DB URL lookup failed. I changed `clusterDomain` to properly and pod was running finally.

**Comment by ruruiye** [comment]
I have the same issue, my cluster domain is `cluster.local` and it still not work. the headless svc has no cluster IP

**Comment by javsalgar** [comment]
Hi,

Could you confirm you are using the latest version of the chart? @rafariossaa implemented changes that should fix the issue

**Comment by ruruiye** [comment]
I think I got the root cause, it's because the repmgr start to monitor before the `livenessProbe` of postgresql is ready, so the headless service can't return the address. I think the solution is either add retry for repmgr or wait for a few seconds before start repmgr

**Comment by javsalgar** [comment]
Hi,

Thank you so much! We will take a look at the PR

**Comment by zffocussss** [comment]
same here

**Comment by sylver** [comment]
Hi,

It seems that's still happening.
I can create a new issue, but that would probably be better to follow up on this one and reopen it if confirmed.

I tried to update the chart to the last version (`6.3.2` atm), hoping the parallel deployment would fix it but I'm facing the same dns resolution issue when the pods try to come back and talk to each other.
No issue during first deployment, but as soon as the primary node switch, that's the end, no way to recover a stable cluster (unless trashing everything, obviously you don't want that).

## Logs

- `api-db-pgpool`
```
2020-12-15 11:33:08: pid 1: ERROR:  failed to make persistent db connection
2020-12-15 11:33:08: pid 1: DETAIL:  connection to host:"api-db-postgresql-0.api-db-postgresql-headless.default.svc.cluster.local:5432" failed
2020-12-15 11:33:08: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 0
2020-12-15 11:33:08: pid 1: WARNING:  failed to connect to PostgreSQL server, getaddrinfo() failed with error "Name or service not known"
2020-12-15 11:33:08: pid 1: ERROR:  failed to make persistent db connection
2020-12-15 11:33:08: pid 1: DETAIL:  connection to host:"api-db-postgresql-1.api-db-postgresql-headless.default.svc.cluster.local:5432" failed
2020-12-15 11:33:08: pid 1: LOG:  find_primary_node: make_persistent_db_connection_noerror failed on node 1
```

- `api-db-postgresql-0`
```
[2020-12-15 11:38:50] [ERROR] connection to database failed
[2020-12-15 11:38:50] [DETAIL] 
could not translate host name "api-db-postgresql-1.api-db-postgresql-headless.default.svc.cluster.local" to address: Name or service not known

[2020-12-15 11:38:50] [DETAIL] attempted to connect using:
  user=repmgr password=KpueCKo3xVtazNAsHzMnJUyzANFiYmm7 connect_timeout=5 dbname=repmgr host=api-db-postgresql-1.api-db-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr
[2020-12-15 11:38:50] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2020-12-15 11:38:50] [HINT] upstream node must be running before repmgrd can start
```

- `api-db-postgresql-1`
```
postgresql-repmgr 11:41:07.52 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 11:41:07.54 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 11:41:07.55 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 11:41:07.56 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 11:41:07.63 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 11:41:07.64 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 11:41:07.77 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 11:41:07.78 INFO  ==> Initializing Repmgr...
postgresql-repmgr 11:41:07.78 INFO  ==> Waiting for primary node...
```

Am I missing something here ?
Does someone knows a workaround ?

Thanks

**Comment by javsalgar** [comment]
Hi,

Thanks for the information. As far is I see this is still not merged. Could you check if this https://github.com/bitnami/bitnami-docker-postgresql-repmgr/pull/28 fixes the issue?

**Comment by sylver** [comment]
@javsalgar Thanks for your answer.
I posted a comment there too, waiting for an answer since that seems related.

Not sure how I can test manually if the PR https://github.com/bitnami/bitnami-docker-postgresql-repmgr/pull/28 fix an issue I have with your `postgresql-ha` helm chart though, could use some help on how doing this so I can give you a feedback.

**Comment by javsalgar** [comment]
A way to test it would be to build the container using the PR above and deploy the chart using that created image.

**Comment by BruceDu521** [comment]
Hi,

I got the same issue but I didn't find the PR mentioned above, is its page still accessible now? Or migrated to a new page?

**Comment by BruceDu521** [comment]
@carrodher Thanks for your reply, I just posted a new separate issue #23589 .

If you need any more details, please let me know.
