### ISSUE TITLE
[bitnami/rabbitmq] Attach existing volume as persistence storage

### ISSUE THREAD

**Issue by rnkhouse** [bitnami/charts#3219]
**Which chart**:
rabbitmq

**Describe the bug**
How can I attach existing volume as persistence storage without using `persistence.existingClaim` param (because I am not using dynamic PersistentVolumeClaim)? Currently, I am using the below settings but, it's not working. and it creates dynamic volume everytime. I want to use existing volume from Azure cloud.

    persistence:
      enabled: true
    extraVolumes:
      - name: data-rabbitmq-0
        azureDisk:
          kind: Managed
          diskName: RABBITMQ_DISK_NAME
          diskURI: RABBITMQ_DISK_URI

**To Reproduce**
Create helm chart using above helm values. I am using AKS cluster and Azure storage class.

**Expected behavior**
It should mount volume on existing volume (Managed Disk by Azure).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, as far as I know, by default the chart is creating a volume by using dynamic volume provisioning but an existing PersistentVolumeClaim can also be defined via `persistence.existingClaim`.

In the case of using `extraVolumes`, you should also specify the `extraVolumeMount` section, something like (pseudo-code):
```yaml
extraVolumeMounts:
  - name: data-rabbitmq-0
    mountPath: /usr/share/extras
    readOnly: true
extraVolumes:
  - name: data-rabbitmq-0
    azureDisk:
      kind: Managed
      diskName: RABBITMQ_DISK_NAME
      diskURI: RABBITMQ_DISK_URI
```

If the issue is related to the permission once mounted the volume, you will need to enable the init container that configures the permissions: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#adjust-permissions-of-the-persistence-volume-mountpoint

**Comment by rnkhouse** [comment]
Hi @carrodher  I installed helm chart using below configs:

    persistence:
      enabled: false
      #existingClaim: RABBITMQ_PVC_NAME
    volumePermissions:
      enabled: true
    extraVolumeMounts:
      - name: data-rabbitmq-0
        mountPath: /opt/bitnami/rabbitmq/var/lib/rabbitmq/
        readOnly: true
    extraVolumes:
      - name: data-rabbitmq-0
        azureDisk:
          kind: Managed
          diskName: RABBITMQ_DISK_NAME
          diskURI: RABBITMQ_DISK_URI

Getting this error:

    14:42:58.66 Welcome to the Bitnami rabbitmq container
    14:42:58.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
    14:42:58.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues
    14:42:58.66
    14:42:58.67 INFO  ==> ** Starting RabbitMQ setup **
    14:42:58.68 INFO  ==> Validating settings in RABBITMQ_* env vars..
    14:42:58.69 INFO  ==> Initializing RabbitMQ...
    touch: cannot touch '/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start': Read-only file system

**Comment by carrodher** [comment]
According to
```
touch: cannot touch '/opt/bitnami/rabbitmq/var/lib/rabbitmq/.start': Read-only file system
```
it seems rabbitmq is trying to write (create a `.start` file) at `/opt/bitnami/rabbitmq/var/lib/rabbitmq/`; but according to your values
```yaml
extraVolumeMounts:
  - name: data-rabbitmq-0
    mountPath: /opt/bitnami/rabbitmq/var/lib/rabbitmq/
    readOnly: true
``` 
this path is configured as `readOnly`, so rabbitmq is failing because it is not able to write in that path. Can you change the volume to make it writable? That should solve this issue

**Comment by rnkhouse** [comment]
@carrodher 
I want to bind the data directory with external volume for persistent data. But, seems like it's not working like this. I tried with this path`/bitnami/rabbitmq/mnesia`

I don't see any error message but the pod is not getting initiated.

I also tried with `/bitnami/rabbitmq/` but it still shows empty directory in volume mount.

When I describe pod:

    data:
        Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
        Medium:
        SizeLimit:  <unset>

**Comment by carrodher** [comment]
Hi, I am glad you were able to fix the permission issue.

About mounting an external volume, did you take a look at [this section in the README](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#persistence)? It explains the default configuration, how to connect an existing PVC, and also how to solve some issues with the permission by initializing an init container.

In the same way, [here](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#persistence-parameters) you can find the parameters related to persistence, just in case you are missing something in your values.

**Comment by rnkhouse** [comment]
@carrodher First of all I tried whatever's in the documentation. But, I don't see an option to attach existing volume directly. I don't want to use `existingClaim` because of some limitations with the AKS cluster. So, what I have is statically created volume and I just want to provide diskname and diskuri for persistent volume. That's why I used:

    - name: data-rabbitmq-0
        azureDisk:
          kind: Managed
          diskName: RABBITMQ_DISK_NAME
          diskURI: RABBITMQ_DISK_URI

I am using this volume (https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume). As you can see volume can be assigned directly to the pod without PersistentVolumeClaim.

Maybe this is a new feature request. Let me share with you the reference as well that I am using with Jenkins helm chart. (https://github.com/helm/charts/tree/master/stable/jenkins#persistence-values). If you will check Jenkins persistence-values, there is an option to provide volume details using `persistence.volum`.

**Comment by carrodher** [comment]
Hi, yes, it seems with the current values is not possible to cover your use case, I think it's something that can be useful but we are a small team with limited resources (more in summer) so I can not guarantee that we can implement it in a short period of time.
On the other hand, contributions are more than welcome via GitHub Pull Requests, we will be happy to review any PR received adding this new feature!

**Comment by yywing** [comment]
```
To 9.0.0
...
persistence.volumes has been removed, as it duplicates the parameter extraVolumes.
...
```

value.yaml
```yaml
    extraVolumes:
      - name: data
        nfs:
          server: "1"
  persistence:
    enabled: false
```

gen k8s config:
```yaml
        - name: data
          nfs:
            server: "1"
        - name: data
          emptyDir: {}
```

So, I cannot disable pvc and use exist volume in all bitnami chart.

**Comment by javsalgar** [comment]
Hi,

I see that you created a different ticket for this. Let's continue the conversation there.
