### ISSUE TITLE
[bitnami/postgresql-ha] Scaling of statefulset replicas is not actually scaling the DB instances though postgresql pod's are scaled

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3431]
**Which chart**:

- `bitnami/postgresql-ha` and `3.4.9`

**Describe the bug**

I have deployed the postgresql-ha helm chart with "5" postgresql replicas, then I have scaled of statefulset replicas to "7"  and noticed postgresql pods are scaled to "7"  but is not actually scaled the DB instances though postgresql pod's are scaled. Please find the clear output .

**To Reproduce**

***Step 1:*** 

Deploy postgresql-ha helm chart with 5 replicas and 2 pgpool replicas.

***Step 2:*** 

```console
[root@masternode1 postgresql-ha]# kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-8546b7b876-z74cw   1/1     Running   0          2m37s
postgresql-ha-pgpool-8546b7b876-z9bgh   1/1     Running   0          2m37s
postgresql-ha-postgresql-0              2/2     Running   0          2m37s
postgresql-ha-postgresql-1              2/2     Running   0          2m6s
postgresql-ha-postgresql-2              2/2     Running   0          100s
postgresql-ha-postgresql-3              2/2     Running   0          66s
postgresql-ha-postgresql-4              2/2     Running   0          48s
```

***Step 3:***

```console
[root@masternode1 postgresql-ha]# kubectl get statefulset
NAME                       READY   AGE
postgresql-ha-postgresql   5/5     27m
```

**Step 4:** Scaled the replicas to 7

```console
[root@masternode1 postgresql-ha]# kubectl scale statefulset postgresql-ha-postgresql --replicas=7
statefulset.apps/postgresql-ha-postgresql scaled
```

***Step 5:***

```console
[root@masternode1 ~]# kubectl get statefulset
NAME                       READY   AGE
postgresql-ha-postgresql   7/7     31m
```

***Step 6:*** 

We can see it is scaled to 7 pods which is exepected and is good so far.

```console
[root@masternode1 ~]# kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-8546b7b876-z74cw   1/1     Running   0          55m
postgresql-ha-pgpool-8546b7b876-z9bgh   1/1     Running   0          55m
postgresql-ha-postgresql-0              2/2     Running   0          55m
postgresql-ha-postgresql-1              2/2     Running   0          54m
postgresql-ha-postgresql-2              2/2     Running   0          54m
postgresql-ha-postgresql-3              2/2     Running   0          53m
postgresql-ha-postgresql-4              2/2     Running   0          53m
postgresql-ha-postgresql-5              2/2     Running   0          26m
postgresql-ha-postgresql-6              2/2     Running   0          21m
```

***Step 7:***

If you look at below output ,only 5 DB instances are running...but i am expecting 7 instances in UP status.

```
testdb=# show pool_nodes;
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 130        | true
            | 0                 |                   |                        | 2020-08-16 15:39:48
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 131        | false
            | 0                 |                   |                        | 2020-08-16 15:40:11
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 150        | false
            | 0                 |                   |                        | 2020-08-16 15:40:53
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 138        | false
            | 0                 |                   |                        | 2020-08-16 15:41:03
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 128        | false
            | 0                 |                   |                        | 2020-08-16 15:41:23
(5 rows)
```

***Expected behavior***

When the replicas of postgresql are scaled to 7 then  we should be seeing 7 db instances in UP state while listing "show pool_nodes"

***Version of Helm and Kubernetes***:

- Output of `helm version`:

```
[root@masternode1 ~]# helm version --short
Client: v2.16.1+gbbdfe5e
Server: v2.16.1+gbbdfe5e
[root@masternode1 ~]#
```

- Output of `kubectl version`:

```
[root@masternode1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
[root@masternode1 ~]#
```

**Additional context**

**Comment by juan131** [comment]
Hi @parvaths1118 

Could you try using `helm upgrade..` instead of `kubectl scale ...`? As it's documented [here](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#production-configuration-and-horizontal-scaling):

> To horizontally scale this chart, you can use the `--replicaCount` flag to modify the number of nodes in your PostgreSQL deployment. Also you can use the values-production.yaml file or modify the parameters shown above.

**Comment by parvaths1118** [comment]
Hi @juan131  ,Thank you for your response.

I have scaled the postgressql replicas using helm upgrade and noticed the instance was scaled properly but all the slaves are disconnected from the master and the streaming is not happening any more.

Please check the output after upgrading the replica's count from "5" to "6"

**testdb=# show pool_nodes;**
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 5          | false
            | 0                 |                   |                        | 2020-08-17 13:24:57
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 0          | false
            | 0                 |                   |                        | 2020-08-17 13:24:59
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 0          | false
            | 0                 |                   |                        | 2020-08-17 13:25:09
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 3          | false
            | 0                 |                   |                        | 2020-08-17 13:25:09
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | primary | 4          | false
            | 0                 |                   |                        | 2020-08-17 13:24:57
 5       | postgresql-ha-postgresql-5.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 2          | true
            | 0                 |                   |                        | 2020-08-17 13:24:44
(6 rows)


**postgres=# select * from pg_stat_replication;**
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | fl
ush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+---
--------+------------+-----------+-----------+------------+---------------+------------
**(0 rows)**

postgres=#

**Comment by juan131** [comment]
Hm... That's weird. Could you please share the exact **values.yaml** and command you used? Thanks in advance

**Comment by parvaths1118** [comment]
Hi @juan131  ,Thank you for your response.
 I have attached values-production yaml


Please find the step by step detailed explaination.

**Step 1 :**  Deploy the helm chart. Please download the values-production.yaml attached. I have configured 5 postgresql replicas and 2 pgpool replicas with persistence volume enabled. 

[root@masternode1 postgresql-ha]# **helm install --name postgresql-ha bitnami/postgresql-ha -f values-production.yaml**
NAME:   postgresql-ha
LAST DEPLOYED: Tue Aug 18 23:27:06 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                    AGE
postgresql-ha-postgresql-hooks-scripts  0s

==> v1/Deployment
NAME                  AGE
postgresql-ha-pgpool  0s

==> v1/NetworkPolicy
NAME           AGE
postgresql-ha  0s

==> v1/Pod(related)
NAME                                   AGE
postgresql-ha-pgpool-8546b7b876-c4n6s  0s
postgresql-ha-pgpool-8546b7b876-zc8lg  0s
postgresql-ha-postgresql-0             0s

==> v1/Secret
NAME                      AGE
postgresql-ha-pgpool      0s
postgresql-ha-postgresql  0s

==> v1/Service
NAME                               AGE
postgresql-ha-pgpool               0s
postgresql-ha-postgresql           0s
postgresql-ha-postgresql-headless  0s
postgresql-ha-postgresql-metrics   0s

==> v1/StatefulSet
NAME                      AGE
postgresql-ha-postgresql  0s


NOTES:

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb

Note: Since NetworkPolicy is enabled, only pods with label "postgresql-ha-client=true" will be able to connect to this PostgreSQL cluster.

To connect to your database from outside the cluster execute the following commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w postgresql-ha-pgpool

    export SERVICE_IP=$(kubectl get svc --namespace default postgresql-ha-pgpool --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h $SERVICE_IP -p 5432  -U postgres -d testdb

[root@masternode1 postgresql-ha]#


**Step 2 :** Please check the status of pods. "kubectl get pods" . This looks good and working as expected.

[root@masternode1 postgresql-ha]# kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-8546b7b876-c4n6s   1/1     Running   0          103s
postgresql-ha-pgpool-8546b7b876-zc8lg   1/1     Running   0          103s
postgresql-ha-postgresql-0              2/2     Running   0          103s
postgresql-ha-postgresql-1              2/2     Running   0          80s
postgresql-ha-postgresql-2              2/2     Running   0          57s
postgresql-ha-postgresql-3              2/2     Running   0          38s
postgresql-ha-postgresql-4              2/2     Running   0          11s
[root@masternode1 postgresql-ha]#


**Step 3 :** I am connecting to database and check the pgpool_nodes status ,one primary instance and 4 standby instances which is working fine.


[root@masternode1 postgresql-ha]# export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
[root@masternode1 postgresql-ha]# kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb
If you don't see a command prompt, try pressing enter.

testdb=# **show pool_nodes;**
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 13         | false
            | 0                 |                   |                        | 2020-08-19 03:27:38
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 4          | false
            | 0                 |                   |                        | 2020-08-19 03:28:03
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 7          | false
            | 0                 |                   |                        | 2020-08-19 03:28:18
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 1          | true
            | 0                 |                   |                        | 2020-08-19 03:28:48
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 2          | false
            | 0                 |                   |                        | 2020-08-19 03:29:08
(5 rows)

testdb=#


**Step 4 :** Checking the status pg_stat_replication ,which seems to be good all the 4 standby instances are connected to master and replication happening..

testdb=# select * from pg_stat_replication;
 pid | usesysid | usename | application_name |  client_addr   | client_hostname | client_port |         backend_start         | backend_xmin |   state   | se
nt_lsn  | write_lsn | flush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+----------------+-----------------+-------------+-------------------------------+--------------+-----------+---
--------+-----------+-----------+------------+-----------+-----------+------------+---------------+------------
 330 |    16385 | repmgr  | walreceiver      | 10.233.70.181  |                 |       48928 | 2020-08-19 03:27:48.589534+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 528 |    16385 | repmgr  | walreceiver      | 10.233.103.219 |                 |       51502 | 2020-08-19 03:28:31.165317+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 411 |    16385 | repmgr  | walreceiver      | 10.233.78.186  |                 |       56824 | 2020-08-19 03:28:04.908165+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
 633 |    16385 | repmgr  | walreceiver      | 10.233.78.187  |                 |       52288 | 2020-08-19 03:28:50.417312+00 |              | streaming | 0/
B001490 | 0/B001490 | 0/B001490 | 0/B001490  |           |           |            |             0 | async
(4 rows)

testdb=#


**Step 5 :** Now I am upgrading the helm chart with just changing replicas of postgresql from "5" to "6" by passing the replicas value from command line using --set flag


[root@masternode1 postgresql-ha]# **helm upgrade postgresql-ha bitnami/postgresql-ha -f values-production.yaml --set postgresql.replicaCount=6**
Release "postgresql-ha" has been upgraded.
LAST DEPLOYED: Tue Aug 18 23:32:05 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                    AGE
postgresql-ha-postgresql-hooks-scripts  4m59s

==> v1/Deployment
NAME                  AGE
postgresql-ha-pgpool  4m59s

==> v1/NetworkPolicy
NAME           AGE
postgresql-ha  4m59s

==> v1/Pod(related)
NAME                                   AGE
postgresql-ha-pgpool-8546b7b876-c4n6s  4m59s
postgresql-ha-pgpool-8546b7b876-zc8lg  4m59s
postgresql-ha-pgpool-d6695575-shnzs    0s
postgresql-ha-postgresql-0             4m59s
postgresql-ha-postgresql-1             4m36s
postgresql-ha-postgresql-2             4m13s
postgresql-ha-postgresql-3             3m54s
postgresql-ha-postgresql-4             3m27s
postgresql-ha-postgresql-5             0s

==> v1/Secret
NAME                      AGE
postgresql-ha-pgpool      4m59s
postgresql-ha-postgresql  4m59s

==> v1/Service
NAME                               AGE
postgresql-ha-pgpool               4m59s
postgresql-ha-postgresql           4m59s
postgresql-ha-postgresql-headless  4m59s
postgresql-ha-postgresql-metrics   4m59s

==> v1/StatefulSet
NAME                      AGE
postgresql-ha-postgresql  4m59s


NOTES:

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb

Note: Since NetworkPolicy is enabled, only pods with label "postgresql-ha-client=true" will be able to connect to this PostgreSQL cluster.

To connect to your database from outside the cluster execute the following commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w postgresql-ha-pgpool

    export SERVICE_IP=$(kubectl get svc --namespace default postgresql-ha-pgpool --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h $SERVICE_IP -p 5432  -U postgres -d testdb

[root@masternode1 postgresql-ha]#



**Step 6 :** Rolling upgrade happened sequentially for all the pods  and replica's are changed to "6" now.Please check the status of pods. "kubectl get pods" .You could find new replica is added .This looks good.

[root@masternode1 postgresql-ha]# kubectl get pods
NAME                                  READY   STATUS     RESTARTS   AGE
postgresql-ha-pgpool-d6695575-dl7qb   1/1     Running    0          96s
postgresql-ha-pgpool-d6695575-shnzs   1/1     Running    0          102s
postgresql-ha-postgresql-0            2/2     Running    0          6m41s
postgresql-ha-postgresql-1            2/2     Running    0          6m18s
postgresql-ha-postgresql-2            0/2     Init:0/1   0          7s
postgresql-ha-postgresql-3            2/2     Running    0          42s
postgresql-ha-postgresql-4            2/2     Running    0          67s
**postgresql-ha-postgresql-5            2/2     Running    0          102s**

**Step 7 :** Now I am connecting to the database and checking the instance status. from the output below we can see another replica is added to the cluster. This is working fine.

[root@masternode1 postgresql-ha]#  export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
[root@masternode1 postgresql-ha]# kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.13.0-debian-10-r55 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb
If you don't see a command prompt, try pressing enter.

testdb=# show pool_nodes;
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 6          | false
            | 100660512         |                   |                        | 2020-08-19 03:35:42
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | primary | 25         | false
            | 0                 |                   |                        | 2020-08-19 03:35:38
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 7          | false
            | 4312              |                   |                        | 2020-08-19 03:36:32
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 4          | false
            | 33559944          |                   |                        | 2020-08-19 03:36:22
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 6          | true
            | 16782728          |                   |                        | 2020-08-19 03:36:32
 5       | postgresql-ha-postgresql-5.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.166667  | standby | 5          | false
            | 33559944          |                   |                        | 2020-08-19 03:36:22
(6 rows)

testdb=#


**Step 8:**  Now check the pg_stat_replication status,all the nodes are disconnected from the master and replication cannot happpen any more. This is the issue .


testdb=# **select * from pg_stat_replication;**
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | fl
ush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+---
--------+------------+-----------+-----------+------------+---------------+------------
**(0 rows)**

testdb=#

Please let me know if any other information is needed.

**Comment by parvaths1118** [comment]
[values-production.txt](https://github.com/bitnami/charts/files/5094086/values-production.txt)

**Comment by juan131** [comment]
Thanks so much!! We're investigating this issue that seems to be related with the primary node not recovering the right status after restarting.

See https://github.com/bitnami/charts/issues/3127

**Comment by parvaths1118** [comment]
Thank you @juan131 ,Is there any timeline when we will have the fix available for this issue ?? we want to use this chart in our production environment as this is fitting our requirement.

**Comment by juan131** [comment]
Hi @parvaths1118 

I am afraid I cannot provide you any ETA, but I know that the team is already working on this issue so I guess there will be a solution published in the next few days.

**Comment by rafariossaa** [comment]
Hi,
  A new container image was released, it should fix the issue. The postgresql-ha chart v3.5.6 uses this new image.

  Could you give it a try and check if it solves the issue for you ?

**Comment by parvaths1118** [comment]
Hi @rafariossaa ,

Thank you for the new image.

I have validated the new image with very good amount of negative test cases,most of the cases are working fine.

I have noticed couple of issues.

**Issue 1  :**  I think we still have issues in scaling the replicas.  I have scaled statefulset from replicas 5 to 6.  New scaled replica is not connected to cluster  pool though replication is working fine. Please see the step by step output

[root@masternode1 ~]# **kubectl get sts**
NAME                       READY   AGE
postgresql-ha-postgresql   5/5     101m

[root@masternode1 ~]# **kubectl scale statefulset postgresql-ha-postgresql --replicas=6**
statefulset.apps/postgresql-ha-postgresql scaled

[root@masternode1 ~]# **kubectl get pods**  [**New stanby replica is scaled as requested**]
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-594677b7cf-89r6t   1/1     Running   0          10m
postgresql-ha-pgpool-594677b7cf-blg6m   1/1     Running   3          103m
postgresql-ha-postgresql-0              2/2     Running   0          8m42s
postgresql-ha-postgresql-1              2/2     Running   1          23m
postgresql-ha-postgresql-2              2/2     Running   2          23m
postgresql-ha-postgresql-3              2/2     Running   2          24m
postgresql-ha-postgresql-4              2/2     Running   2          24m
**postgresql-ha-postgresql-5              2/2     Running   0          67s**

**testdb=# show pool_nodes;**  [**New instance is not connected to the cluster ,if you look at the out  new scaled replica "postgresql-ha-postgresql-5" is missing in the cluster pool**]
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 29         | false
            | 0                 |                   |                        | 2020-08-25 05:42:08
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | primary | 35         | true
            | 0                 |                   |                        | 2020-08-25 05:39:33
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 36         | false
            | 0                 |                   |                        | 2020-08-25 05:39:33
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 36         | false
            | 0                 |                   |                        | 2020-08-25 05:39:33
 4       | postgresql-ha-postgresql-4.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.200000  | standby | 31         | false
            | 0                 |                   |                        | 2020-08-25 05:39:33
(5 rows)

**testdb=# select * from pg_stat_replication;** [**replication is working fine,from the output below we can see all the 5 standby instances are connected and streaming**]
 pid  | usesysid | usename | application_name |  client_addr   | client_hostname | client_port |         backend_start         | backend_xmin |   state   |
sent_lsn  | write_lsn  | flush_lsn  | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
------+----------+---------+------------------+----------------+-----------------+-------------+-------------------------------+--------------+-----------+--
----------+------------+------------+------------+-----------+-----------+------------+---------------+------------
 1479 |    16385 | repmgr  | walreceiver      | 10.233.78.223  |                 |       37458 | 2020-08-25 05:36:08.375975+00 |              | streaming | 0
/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 |           |           |            |             0 | async
 1480 |    16385 | repmgr  | walreceiver      | 10.233.103.255 |                 |       40230 | 2020-08-25 05:36:08.524903+00 |              | streaming | 0
/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 |           |           |            |             0 | async
 1485 |    16385 | repmgr  | walreceiver      | 10.233.103.254 |                 |       60096 | 2020-08-25 05:36:08.756463+00 |              | streaming | 0
/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 |           |           |            |             0 | async
 4971 |    16385 | repmgr  | walreceiver      | 10.233.70.208  |                 |       47494 | 2020-08-25 05:49:27.868511+00 |              | streaming | 0
/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 |           |           |            |             0 | async
 2864 |    16385 | repmgr  | walreceiver      | 10.233.78.225  |                 |       35698 | 2020-08-25 05:41:54.870221+00 |              | streaming | 0
/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 | 0/2D0038B0 |           |           |            |             0 | async
(5 rows)

**Issue 2 :**  Readiness probe is always failing as shown below and also some error while mounting the pod. Please check the pod describe output below.

  Type     Reason            Age        From                                         Message
  ----     ------            ----       ----                                         -------
  **Warning  FailedScheduling  <unknown>  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-0": pod has unbound immediate PersistentVolumeClaims**
  Normal   Scheduled         <unknown>  default-scheduler                            Successfully assigned default/postgresql-ha-postgresql-0 to workernode3.test.nimblestorage.com
  Normal   Pulling           114s       kubelet, workernode3.test.nimblestorage.com  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            112s       kubelet, workernode3.test.nimblestorage.com  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Normal   Created           112s       kubelet, workernode3.test.nimblestorage.com  Created container init-chmod-data
  Normal   Started           112s       kubelet, workernode3.test.nimblestorage.com  Started container init-chmod-data
  Normal   Pulled            111s       kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6" already present on machine
  Normal   Created           111s       kubelet, workernode3.test.nimblestorage.com  Created container postgresql
  Normal   Started           111s       kubelet, workernode3.test.nimblestorage.com  Started container postgresql
  Normal   Pulled            111s       kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r173" already present on machine
  Normal   Created           111s       kubelet, workernode3.test.nimblestorage.com  Created container metrics
  Normal   Started           111s       kubelet, workernode3.test.nimblestorage.com  Started container metrics
  Warning  Unhealthy         105s       kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: Get http://10.233.70.214:9187/: dial tcp 10.233.70.214:9187: connect: connection refused
  **Warning  Unhealthy         100s       kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?**
[root@masternode1 postgresql-ha]#

Please let me know if you prefer to open a new issue. Thank you for all your help in fixing the issues.

Let me know if any additional information is needed.

**Comment by rafariossaa** [comment]
Hi,
  I will try to explain what is happening here, first a bit of context:
  When you deploy a postgresql-ha chart with a number of nodes, let's say 5 postgresql. The chart will pass to pgpool pod initialization script the nodes that are part of the cluster, and then the `pgpool.conf` file is generated. The initialization only occurs when starting the pod the first time.

  So, if you scale the statefulset by using `kubectl`, pgpool is not be aware of the new nodes. To add them, in a no-container environment, you will need to edit the pgpool config file and restart pgpool. In this case, you will need to upgrade the helm deployment, as indicated [here](https://github.com/bitnami/charts/issues/3431#issuecomment-674836237). This will redeploy the needed components. With the new `postgresql-repmgr` image there should not be any issue.

  About the readiness probe, it is not very clear to me from which pod is that log. Is it from the 5 first nodes or is it from the new two nodes ?.  In any case, readiness test are meant to fail until the pod is "ready" (it passes the [test](https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L197)).

**Comment by parvaths1118** [comment]
Hi @rafariossaa ,

Thank you so much for the explanation.

Now I have validated using helm upgrade,i could upgrade the replicas from 5 to 6 successfully .Streaming also worked fine.

But i found some issue when i downgrade the replicas from 6 to 4. Please find the output below.

**[root@masternode1 ~]# kubectl get pods**  [ **Please note there are 6 pod's currently running**]
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-6db986fb56-7qqbr   1/1     Running   0          21m
postgresql-ha-pgpool-6db986fb56-mqkbq   1/1     Running   0          21m
postgresql-ha-postgresql-0              2/2     Running   1          19m
postgresql-ha-postgresql-1              2/2     Running   0          20m
postgresql-ha-postgresql-2              2/2     Running   1          20m
postgresql-ha-postgresql-3              2/2     Running   1          21m
postgresql-ha-postgresql-4              2/2     Running   1          21m
postgresql-ha-postgresql-5              2/2     Running   1          21m

[root@masternode1 postgresql-ha]# **helm upgrade postgresql-ha bitnami/postgresql-ha -f values-production.yaml --set postgresql.replicaCount=4**
Release "postgresql-ha" has been upgraded.
LAST DEPLOYED: Tue Aug 25 23:29:19 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                                    AGE
postgresql-ha-postgresql-hooks-scripts  34m

==> v1/Deployment
NAME                  AGE
postgresql-ha-pgpool  34m

==> v1/NetworkPolicy
NAME           AGE
postgresql-ha  34m

==> v1/Pod(related)
NAME                                   AGE
postgresql-ha-pgpool-6db986fb56-7qqbr  22m
postgresql-ha-pgpool-6db986fb56-mqkbq  22m
postgresql-ha-pgpool-79dbd65bdb-clm8x  0s
postgresql-ha-postgresql-0             20m
postgresql-ha-postgresql-1             21m
postgresql-ha-postgresql-2             21m
postgresql-ha-postgresql-3             22m
postgresql-ha-postgresql-4             22m
postgresql-ha-postgresql-5             22m

==> v1/Secret
NAME                      AGE
postgresql-ha-pgpool      34m
postgresql-ha-postgresql  34m

==> v1/Service
NAME                               AGE
postgresql-ha-pgpool               34m
postgresql-ha-postgresql           34m
postgresql-ha-postgresql-headless  34m
postgresql-ha-postgresql-metrics   34m

==> v1/StatefulSet
NAME                      AGE
postgresql-ha-postgresql  34m


NOTES:

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed through Pgpool via port 5432 on the following DNS name from within your cluster:

    postgresql-ha-pgpool.default.svc.cluster.local

Pgpool acts as a load balancer for PostgreSQL and forward read/write connections to the primary node while read-only connections are forwarded to standby nodes.

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To get the password for "repmgr" run:

    export REPMGR_PASSWORD=$(kubectl get secret --namespace default postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" \
        --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb

Note: Since NetworkPolicy is enabled, only pods with label "postgresql-ha-client=true" will be able to connect to this PostgreSQL cluster.

To connect to your database from outside the cluster execute the following commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w postgresql-ha-pgpool

    export SERVICE_IP=$(kubectl get svc --namespace default postgresql-ha-pgpool --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h $SERVICE_IP -p 5432  -U postgres -d testdb


**[root@masternode1 postgresql-ha]# kubectl get pods**    [ **we can see pod's are downgraded from 6 to 4**]
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-79dbd65bdb-clm8x   1/1     Running   1          4m42s
postgresql-ha-pgpool-79dbd65bdb-p5qjc   1/1     Running   0          4m32s
postgresql-ha-postgresql-0              2/2     Running   0          107s
postgresql-ha-postgresql-1              2/2     Running   1          3m29s
postgresql-ha-postgresql-2              2/2     Running   2          4m1s
postgresql-ha-postgresql-3              2/2     Running   2          4m28s

[root@masternode1 postgresql-ha]# kubectl run postgresql-ha-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6 --env="PGPASSWORD=$POSTGRES_PASSWORD" --labels="postgresql-ha-client=true" --command -- psql -h postgresql-ha-pgpool -p 5432 -U postgres -d testdb
If you don't see a command prompt, try pressing enter.

**testdb=# show pool_nodes;**
 node_id |                                        hostname                                        | port | status | lb_weight |  role   | select_cnt | load_b
alance_node | replication_delay | replication_state | replication_sync_state | last_status_change
---------+----------------------------------------------------------------------------------------+------+--------+-----------+---------+------------+-------
------------+-------------------+-------------------+------------------------+---------------------
 0       | postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.250000  | standby | 30         | true
            | 11864             |                   |                        | 2020-08-26 03:33:32
 1       | postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.250000  | primary | 16         | false
            | 0                 |                   |                        | 2020-08-26 03:33:32
 2       | postgresql-ha-postgresql-2.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.250000  | standby | 15         | false
            | 0                 |                   |                        | 2020-08-26 03:33:34
 3       | postgresql-ha-postgresql-3.postgresql-ha-postgresql-headless.default.svc.cluster.local | 5432 | up     | 0.250000  | standby | 18         | false
            | 0                 |                   |                        | 2020-08-26 03:33:34
(4 rows)

**testdb=# select * from pg_stat_replication;** [**Please check below output ,no standby instances are connected to master and no replication is happening**]
 pid | usesysid | usename | application_name | client_addr | client_hostname | client_port | backend_start | backend_xmin | state | sent_lsn | write_lsn | fl
ush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state
-----+----------+---------+------------------+-------------+-----------------+-------------+---------------+--------------+-------+----------+-----------+---
--------+------------+-----------+-----------+------------+---------------+------------
**(0 rows)**

testdb=#

**Comment by rafariossaa** [comment]
Hi,
  Scaling down worked for me, I think the issue here is that you need set the passwords, because if not they are randomly regenerated again when upgrading the chart to scale it down.
  These are my changes from the original `values.yaml`, I set `debug: true` just to get more info in the logs.
```
$ diff values.yaml_original values.yaml
46c46
<   debug: false
---
>   debug: true
68c68
<   debug: false
---
>   debug: true
219c219
<   # password:
---
>   password: pgpasswd
247c247
<   # repmgrPassword:
---
>   repmgrPassword: repmgrpasswd
```

I installed the chart with:
```
$ helm install mypg -f values.yaml --set postgresql.replicaCount=6 .
```
and waited until all the nodes are stable. Then I upgraded the chart to scale it down with:
```
$ helm upgrade mypg -f values.yaml --set postgresql.replicaCount=4 .
```

This is the final state, a couple of nodes where killed and the rest were restarted. As you can see the where restarted in reverse order, from node 3 to node 0. The pgpool node was also recreated.
When restarting, the nodes needs to decided again which one is the primary, in some cases, you will see some errors in the logs but finally the node get restarted and re-added to the cluster.

```
NAME                                             READY   STATUS    RESTARTS   AGE
pod/mypg-postgresql-ha-pgpool-6774f797dd-vmtt2   1/1     Running   1          4m10s
pod/mypg-postgresql-ha-postgresql-0              1/1     Running   1          2m30s
pod/mypg-postgresql-ha-postgresql-1              1/1     Running   0          2m53s
pod/mypg-postgresql-ha-postgresql-2              1/1     Running   1          3m24s
pod/mypg-postgresql-ha-postgresql-3              1/1     Running   1          3m55s
pod/web-557f59c6cf-ggq2t                         1/1     Running   0          5d16h
```


```
kubectl run mypg-postgresql-ha-client --rm --tty -i --restart='Never' --namespace rafael --image docker.io/bitnami/postgresql-repmgr:11.9.0-debian-10-r3 --env="PGPASSWORD=$POSTGRES_PASSWORD"          --command -- psql -h mypg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres
If you don't see a command prompt, try pressing enter.
psql (11.9)
Type "help" for help.

postgres=# show pool_nodes;
 node_id |                                            hostname                                             
| port | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay | replication_st
ate | replication_sync_state | last_status_change  
---------+-------------------------------------------------------------------------------------------------
+------+--------+-----------+---------+------------+-------------------+-------------------+---------------
----+------------------------+---------------------
 0       | mypg-postgresql-ha-postgresql-0.mypg-postgresql-ha-postgresql-headless.rafael.svc.cluster.local 
| 5432 | up     | 0.250000  | standby | 3          | false             | 0                 |               
    |                        | 2020-08-26 08:17:57
 1       | mypg-postgresql-ha-postgresql-1.mypg-postgresql-ha-postgresql-headless.rafael.svc.cluster.local 
| 5432 | up     | 0.250000  | primary | 8          | false             | 0                 |               
    |                        | 2020-08-26 08:17:12
 2       | mypg-postgresql-ha-postgresql-2.mypg-postgresql-ha-postgresql-headless.rafael.svc.cluster.local 
| 5432 | up     | 0.250000  | standby | 5          | true              | 0                 |               
    |                        | 2020-08-26 08:17:47
 3       | mypg-postgresql-ha-postgresql-3.mypg-postgresql-ha-postgresql-headless.rafael.svc.cluster.local 
| 5432 | up     | 0.250000  | standby | 8          | false             | 0                 |               
    |                        | 2020-08-26 08:17:47
(4 rows)
```
You can see that now the primary node is `mypg-postgresql-ha-postgresql-1`.

```
$ kubectl exec -it pod/mypg-postgresql-ha-postgresql-1  bash I have no name!@mypg-postgresql-ha-postgresql-1:/$ PGPASSWORD=$POSTGRES_PASSWORD psql -h mypg-postgresql-ha-pgpool -p 5432 -U postgres -d postgres
psql (11.9)
Type "help" for help.

postgres=# select * from pg_stat_replication;
 pid | usesysid | usename | application_name | client_addr  | client_hostname | client_port |         backe
nd_start         | backend_xmin |   state   |  sent_lsn  | write_lsn  | flush_lsn  | replay_lsn | write_lag
 | flush_lag | replay_lag | sync_priority | sync_state 
-----+----------+---------+------------------+--------------+-----------------+-------------+--------------
-----------------+--------------+-----------+------------+------------+------------+------------+----------
-+-----------+------------+---------------+------------
 452 |    16384 | repmgr  | walreceiver      | 100.121.0.25 |                 |       46118 | 2020-08-26 08
:17:28.68287+00  |              | streaming | 0/18001A10 | 0/18001A10 | 0/18001A10 | 0/18001A10 |          
 |           |            |             0 | async
 455 |    16384 | repmgr  | walreceiver      | 100.110.0.16 |                 |       37228 | 2020-08-26 08
:17:29.158318+00 |              | streaming | 0/18001A10 | 0/18001A10 | 0/18001A10 | 0/18001A10 |          
 |           |            |             0 | async
 528 |    16384 | repmgr  | walreceiver      | 100.115.0.1  |                 |       59974 | 2020-08-26 08
:17:43.514995+00 |              | streaming | 0/18001A10 | 0/18001A10 | 0/18001A10 | 0/18001A10 |          
 |           |            |             0 | async
(3 rows)

postgres=# 
```

Could you try by setting the passwords in the `values.yaml` ?

**Comment by parvaths1118** [comment]
Thank you @rafariossaa ,

I have verified as per your suggestion and downgrade worked fine.

Regarding Readiness probe,it is always failing either fresh deployment or upgrade. Kindly can you check  ?

Just FYI,I am working on postgresql-ha helm chart.

Regards
SridharP

**Comment by juan131** [comment]
HI @parvaths1118 

Are you talking about the readiness probes on Pgpool or the ones for the PostgreSQL container?
Could you also the output of the command `kubectl describe NAME_OF_THE_POD`?

Thanks in advance

**Comment by parvaths1118** [comment]
Hi @juan131 ,

Thank you for your response.

I have deployed postgresql-ha with 4 postgresql replicas and 2 pgpool replicas. Here i have describe the each pod including pgpool,i could see readiness probe is failed in all the pods.

**Step 1** : **kubectl get pods** 

[root@masternode1 postgresql-ha]# kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
postgresql-ha-pgpool-79dbd65bdb-9qfvb   1/1     Running   0          3m49s
postgresql-ha-pgpool-79dbd65bdb-t69vp   1/1     Running   0          3m49s
postgresql-ha-postgresql-0              2/2     Running   0          3m49s
postgresql-ha-postgresql-1              2/2     Running   0          3m28s
postgresql-ha-postgresql-2              2/2     Running   0          3m10s
postgresql-ha-postgresql-3              2/2     Running   0          2m51s

**Step 2 :**  kubectl describe pod postgresql-ha-postgresql-0

Events:
  Type     Reason            Age                    From                                         Message
  ----     ------            ----                   ----                                         -------
  Warning  FailedScheduling  5m55s (x2 over 5m55s)  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         5m53s                  default-scheduler                            Successfully assigned default/postgresql-ha-postgresql-0 to workernode3.test.nimblestorage.com
  Normal   Pulling           5m53s                  kubelet, workernode3.test.nimblestorage.com  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            5m50s                  kubelet, workernode3.test.nimblestorage.com  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Normal   Created           5m50s                  kubelet, workernode3.test.nimblestorage.com  Created container init-chmod-data
  Normal   Started           5m50s                  kubelet, workernode3.test.nimblestorage.com  Started container init-chmod-data
  Normal   Pulled            5m49s                  kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6" already present on machine
  Normal   Created           5m49s                  kubelet, workernode3.test.nimblestorage.com  Created container postgresql
  Normal   Started           5m49s                  kubelet, workernode3.test.nimblestorage.com  Started container postgresql
  Normal   Pulled            5m49s                  kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r173" already present on machine
  Normal   Created           5m49s                  kubelet, workernode3.test.nimblestorage.com  Created container metrics
  Normal   Started           5m49s                  kubelet, workernode3.test.nimblestorage.com  Started container metrics
  **Warning  Unhealthy         5m44s                  kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: psql: could not connect to server: Connection refused
           Is the server running on host "127.0.0.1" and accepting
           TCP/IP connections on port 5432?**
[root@masternode1 postgresql-ha]# 

**Step 3: kubectl describe pod postgresql-ha-postgresql-3**

Events:
  Type     Reason            Age                    From                                         Message
  ----     ------            ----                   ----                                         -------
  Warning  FailedScheduling  9m11s (x2 over 9m11s)  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-3": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         9m10s                  default-scheduler                            Successfully assigned default/postgresql-ha-postgresql-3 to workernode3.test.nimblestorage.com
  Normal   Pulling           9m9s                   kubelet, workernode3.test.nimblestorage.com  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            9m7s                   kubelet, workernode3.test.nimblestorage.com  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Normal   Created           9m7s                   kubelet, workernode3.test.nimblestorage.com  Created container init-chmod-data
  Normal   Started           9m7s                   kubelet, workernode3.test.nimblestorage.com  Started container init-chmod-data
  Normal   Created           9m6s                   kubelet, workernode3.test.nimblestorage.com  Created container postgresql
  Normal   Pulled            9m6s                   kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6" already present on machine
  Normal   Started           9m6s                   kubelet, workernode3.test.nimblestorage.com  Started container postgresql
  Normal   Pulled            9m6s                   kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r173" already present on machine
  Normal   Created           9m6s                   kubelet, workernode3.test.nimblestorage.com  Created container metrics
  Normal   Started           9m5s                   kubelet, workernode3.test.nimblestorage.com  Started container metrics
  **Warning  Unhealthy         9m                     kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: Get http://10.233.70.6:9187/: dial tcp 10.233.70.6:9187: connect: connection refused
  Warning  Unhealthy         8m58s                  kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: psql: FATAL:  the database system is starting up**
[root@masternode1 postgresql-ha]# 

**Step 4:  kubectl describe pod postgresql-ha-postgresql-3**

Events:
  Type     Reason            Age                From                                         Message
  ----     ------            ----               ----                                         -------
  Warning  FailedScheduling  10m (x2 over 10m)  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-3": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         10m                default-scheduler                            Successfully assigned default/postgresql-ha-postgresql-3 to workernode3.test.nimblestorage.com
  Normal   Pulling           10m                kubelet, workernode3.test.nimblestorage.com  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            10m                kubelet, workernode3.test.nimblestorage.com  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Normal   Created           10m                kubelet, workernode3.test.nimblestorage.com  Created container init-chmod-data
  Normal   Started           10m                kubelet, workernode3.test.nimblestorage.com  Started container init-chmod-data
  Normal   Created           10m                kubelet, workernode3.test.nimblestorage.com  Created container postgresql
  Normal   Pulled            10m                kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6" already present on machine
  Normal   Started           10m                kubelet, workernode3.test.nimblestorage.com  Started container postgresql
  Normal   Pulled            10m                kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r173" already present on machine
  Normal   Created           10m                kubelet, workernode3.test.nimblestorage.com  Created container metrics
  **Normal   Started           10m                kubelet, workernode3.test.nimblestorage.com  Started container metrics
  Warning  Unhealthy         10m                kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: Get http://10.233.70.6:9187/: dial tcp 10.233.70.6:9187: connect: connection refused
  Warning  Unhealthy         10m                kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: psql: FATAL:  the database system is starting up**

**Step 4 :  kubectl describe pod postgresql-ha-postgresql-2**
Events:
  Type     Reason            Age                From                                         Message
  ----     ------            ----               ----                                         -------
  Warning  FailedScheduling  13m (x2 over 13m)  default-scheduler                            error while running "VolumeBinding" filter plugin for pod "postgresql-ha-postgresql-2": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         13m                default-scheduler                            Successfully assigned default/postgresql-ha-postgresql-2 to workernode2.test.nimblestorage.com
  Normal   Pulling           13m                kubelet, workernode2.test.nimblestorage.com  Pulling image "docker.io/bitnami/minideb:buster"
  Normal   Pulled            13m                kubelet, workernode2.test.nimblestorage.com  Successfully pulled image "docker.io/bitnami/minideb:buster"
  Normal   Created           13m                kubelet, workernode2.test.nimblestorage.com  Created container init-chmod-data
  Normal   Started           13m                kubelet, workernode2.test.nimblestorage.com  Started container init-chmod-data
  Normal   Pulled            13m                kubelet, workernode2.test.nimblestorage.com  Container image "docker.io/bitnami/postgresql-repmgr:10.14.0-debian-10-r6" already present on machine
  Normal   Created           13m                kubelet, workernode2.test.nimblestorage.com  Created container postgresql
  Normal   Started           13m                kubelet, workernode2.test.nimblestorage.com  Started container postgresql
  Normal   Pulled            13m                kubelet, workernode2.test.nimblestorage.com  Container image "docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r173" already present on machine
  Normal   Created           13m                kubelet, workernode2.test.nimblestorage.com  Created container metrics
  Normal   Started           13m                kubelet, workernode2.test.nimblestorage.com  Started container metrics

**Step 5 :  kubectl describe pod postgresql-ha-pgpool-79dbd65bdb-9qfvb**

Events:
  Type     Reason     Age                From                                         Message
  ----     ------     ----               ----                                         -------
  Normal   Scheduled  15m                default-scheduler                            Successfully assigned default/postgresql-ha-pgpool-79dbd65bdb-9qfvb to workernode1.test.nimblestorage.com
  Normal   Pulled     15m                kubelet, workernode1.test.nimblestorage.com  Container image "docker.io/bitnami/pgpool:4.1.2-debian-10-r74" already present on machine
  Normal   Created    15m                kubelet, workernode1.test.nimblestorage.com  Created container pgpool
  Normal   Started    15m                kubelet, workernode1.test.nimblestorage.com  Started container pgpool
  **Warning  Unhealthy  15m (x3 over 15m)  kubelet, workernode1.test.nimblestorage.com  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off**

**Step 7:  kubectl describe pod postgresql-ha-pgpool-79dbd65bdb-t69vp**
Events:
  Type     Reason     Age                From                                         Message
  ----     ------     ----               ----                                         -------
  Normal   Scheduled  17m                default-scheduler                            Successfully assigned default/postgresql-ha-pgpool-79dbd65bdb-t69vp to workernode3.test.nimblestorage.com
  Normal   Pulled     17m                kubelet, workernode3.test.nimblestorage.com  Container image "docker.io/bitnami/pgpool:4.1.2-debian-10-r74" already present on machine
  Normal   Created    17m                kubelet, workernode3.test.nimblestorage.com  Created container pgpool
  Normal   Started    17m                kubelet, workernode3.test.nimblestorage.com  Started container pgpool
  **Warning  Unhealthy  16m (x3 over 16m)  kubelet, workernode3.test.nimblestorage.com  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off**

**Comment by juan131** [comment]
Hi @parvaths1118 

Regarding PostgreSQL pods, it looks like the readiness probes fail while the container was being initialized, but after a while they are successful. That's why you obtain "0 restarts" when running `kubectl get pods`, and the warning event obtained in the `kubectl describe` commands are not repeated. Nothing to worry about here.

Regarding Pgpool pods, it seems the warning is repeated several times (see `(x3 over 15m)`) but again not enough time to restart the pod. I think it's related (again) with the backend not being ready yet.

**Comment by parvaths1118** [comment]
Hi @juan131 ,

Thank you .As you and your team addressed all the issues mentioned in this ticket,I am closing this ticket.

Thanks again for your help.
