### ISSUE TITLE
[BUG]8.4.0 docker image / Redis Helm Chart 24.0.4 error for opt/bitnami/redis/lib/redis/modules/redisearch.so

### ISSUE THREAD

**Issue by colasfredo** [bitnami/charts#36417]
### Name and Version

bitnami/charts/tree/main/bitnami/redis 24.0.4

### What steps will reproduce the bug?

**Describe the bug**
Using the 8.4.0 Docker image and the Redis Helm Chart 24.0.4.
with default values in values.yaml for the `commonConfiguration` parameter : 

```yaml
commonConfiguration: |-
  # Enable ReJSON y Redisearch
  loadmodule /opt/bitnami/redis/lib/redis/modules/redisearch.so
  loadmodule /opt/bitnami/redis/lib/redis/modules/rejson.so
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
```

Redis deployment is crashing, by throwing an error in redis pod in CrashLoopBackOff with the following error:
```
Module /opt/bitnami/redis/lib/redis/modules/redisearch.so failed to load: /opt/bitnami/redis/lib/redis/modules/redisearch.so: cannot open shared object file: No such file or directory
Can't load module from /opt/bitnami/redis/lib/redis/modules/redisearch.so: server aborting
```

A short description of the bug.

**To reproduce**

Steps to reproduce the behavior and/or a minimal code sample.
use redis image **8.4.0** and redis helm chart **24.0.4** with `commonConfiguration` set in _values.yaml_ like this:
```yaml
commonConfiguration: |-
  # Enable ReJSON y Redisearch
  loadmodule /opt/bitnami/redis/lib/redis/modules/redisearch.so
  loadmodule /opt/bitnami/redis/lib/redis/modules/rejson.so
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly yes
  # Disable RDB persistence, AOF persistence already enabled.
  save "
```

### What is the expected behavior?

Redis helm deployment must work ^^

**Comment by piotrplenik** [comment]
We faced the same error after bumping the chart from 19.3.4 to 23.2.12. 
In our case, the root cause was only with replicas sts, and the release was via ArgoCD. 
ArgoCD: update master but keep old replicas. 
As a solution, we had to remove the replica STS.

**Comment by jotamartos** [comment]
Hi @colasfredo,

Are you using the private offering or did you build the container image by your own? I'm asking this because the "bitnami/charts/tree/main/bitnami/redis" public chart was not updated to version 24.x and it's running version 8.2 of Redis

https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml

If you are using the private offering, I just deployed the latest version of the chart (24.1.0, your versioning may be different) and it was deployed successfully using the default parameters

```
$ kubectl get all
NAME                   READY   STATUS    RESTARTS   AGE
pod/redis-master-0     1/1     Running   0          106s
pod/redis-replicas-0   1/1     Running   0          106s
pod/redis-replicas-1   1/1     Running   0          66s
pod/redis-replicas-2   1/1     Running   0          40s

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/my-gateway-nginx   ClusterIP   172.20.237.207   <none>        80/TCP,443/TCP   19m
service/redis-headless     ClusterIP   None             <none>        6379/TCP         107s
service/redis-master       ClusterIP   172.20.217.88    <none>        6379/TCP         107s
service/redis-replicas     ClusterIP   172.20.112.41    <none>        6379/TCP         107s

NAME                              READY   AGE
statefulset.apps/redis-master     1/1     108s
statefulset.apps/redis-replicas   3/3     108s
```

> In this case I used the debian-12-based chart, but let me know if you are using any other distro. 

If you are running an upgrade, can you check what @piotrplenik mentioned above? 

Thanks

**Comment by colasfredo** [comment]
> https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml

Thanks for answering, i tried by following this link :
https://artifacthub.io/packages/helm/bitnami/redis i also tried with chart 24.1.0 and i still have the issue.

but when following your link : 
https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml
your values.yaml doesn't have redisearch enabled : 
https://github.com/bitnami/charts/blob/8b08cd4774e6847cf3e76f39622d033404de4a4b/bitnami/redis/values.yaml#L195

and here in this values.yaml : 
https://artifacthub.io/packages/helm/bitnami/redis?modal=values
redisearch is by default enabled

I am confused

**Comment by jotamartos** [comment]
Hi @colasfredo,

github.com/bitnami/charts is not updated anymore since the BSI change announce [here](https://github.com/bitnami/charts/issues/35164).

Regarding the information in artifachub.io, the chart is updated there because Bitnami Redis is part of the free BSI offering. You can get more information from the previous link and dockerhub

https://hub.docker.com/r/bitnamicharts/redis

```
helm install my-release oci://registry-1.docker.io/bitnamicharts/redis
``` 

As the Bitnami Redis docker image is also [available in dockerhub](https://hub.docker.com/r/bitnami/redis), the installation works as expected. 

```
$ helm install redis oci://registry-1.docker.io/bitnamicharts/redis

Pulled: registry-1.docker.io/bitnamicharts/redis:24.1.0
Digest: sha256:cba710f5ad93734be123a40f877ee805dd0e952c01afd19fb93ad1256754b599
W1230 11:53:27.566317   70562 warnings.go:70] spec.SessionAffinity is ignored for headless services
NAME: redis
LAST DEPLOYED: Tue Dec 30 11:53:27 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: redis
CHART VERSION: 24.1.0
APP VERSION: 8.4.0
...
$ kubectl get pods 
NAME               READY   STATUS    RESTARTS   AGE
redis-master-0     1/1     Running   0          87s
redis-replicas-0   1/1     Running   0          87s
redis-replicas-1   1/1     Running   0          56s
redis-replicas-2   1/1     Running   0          35s
```

Does this work for you?
