### ISSUE TITLE
[owncloud] mariadb fails to start

### ISSUE THREAD

**Issue by brianmay** [bitnami/charts#5351]
**Which chart**:
owncloud 10.1.0

**Describe the bug**

mariadb fails to start without any errors:

```
$ kubectl logs -n owncloud  owncloud-mariadb-0         
mariadb 00:11:49.46 
mariadb 00:11:49.47 Welcome to the Bitnami mariadb container
mariadb 00:11:49.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 00:11:49.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 00:11:49.47 
mariadb 00:11:49.47 INFO  ==> ** Starting MariaDB setup **
mariadb 00:11:49.49 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 00:11:49.49 INFO  ==> Initializing mariadb database
mariadb 00:11:49.50 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mariadb 00:11:49.51 INFO  ==> Using persisted data
mariadb 00:11:49.53 INFO  ==> Running mysql_upgrade
mariadb 00:11:49.53 INFO  ==> Starting mariadb in background
mariadb 00:11:51.56 INFO  ==> Stopping mariadb
```

**To Reproduce**

1. Upgrade owncloud to 10.1.10

(Any restart of the mariadb I think might actually cause this)

**Expected behavior**

mariadb should start correctly, or at least log an error that I can use to diagnose problem.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T12:07:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @brianmay 

It looks like some issue with the credentials due to upgrading ownCloud without passing the MariaDB credentials (I mean, without setting the parameters `mariadb.auth.rootPassword` and `mariadb.auth.password`). This is a common mistake, and it's documented in our Troubleshooting guideline, see:

- https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

Could you please ensure you pass the right credentials?

**Comment by brianmay** [comment]
Huh? I don't see any errors regarding bad credentials. Is that normal?

In any case, I did see that, and I believe I am passing the correct credentials. Furthermore, when I supplied the credentials, I checked if there were any differences recorded to the Kubernetes secrets, and didn't see anything significant.

(side note: I would actually prefer it myself if you were forced to enter the credentials on the first install - it would give increased confidence that upgrades are going to work and I didn't get something stupid wrong when copying the automatically generated passwords).

I could destroy this installation and recreate from scratch if necessarily, but I would like to have a good understanding of what has gone wrong first, so I don't re-encounter the same issue again.

**Comment by juan131** [comment]
Hi @brianmay 

> I would actually prefer it myself if you were forced to enter the credentials on the first install 

That's done on recent versions of the chart, to be more precise, starting with version **10.0.0**. If you try to upgrade the chart without passing the database credentials, it throws an error and abort the upgrade process.

> I don't see any errors regarding bad credentials. Is that normal?

Yes, the container throws minimal information by default. However, if you upgrade your release setting `--set mariadb.image.debug=true`, the verbosity of MariaDB container logs will be increased and you should see more information about the reason why the initialization process crashes.

**Comment by brianmay** [comment]
Thanks for this. It looks like it really is a password issue. Which seems a little bit surprising actually.

```
Version: '10.5.8-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2021-02-02  8:44:24 3 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
FATAL ERROR: Upgrade failed
```

Wonder if there is any easy way to reset the password. Might be difficult, because the container is immediately destroyed so I can't do anything with it. Will have think about this.

**Comment by juan131** [comment]
Hi @brianmay 

As it's explained in the [TroubleShoting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases) I shared before, you can rollback your helm release. That should fix the issue with the credentials.

**Comment by brianmay** [comment]
No, it didn't help. Got the exact same password problem. After much work, I finally managed to trick mariadb into resetting the passwords.

But unfortunately owncloud still doesn't work:

```
kubectl logs -n owncloud owncloud-5f5fb5c447-rt6wd
owncloud 10:05:53.19 
owncloud 10:05:53.20 Welcome to the Bitnami owncloud container
owncloud 10:05:53.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-owncloud
owncloud 10:05:53.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-owncloud/issues
owncloud 10:05:53.20 
owncloud 10:05:53.21 INFO  ==> ** Starting ownCloud setup **
owncloud 10:05:53.22 INFO  ==> Configuring the HTTP port
owncloud 10:05:53.23 INFO  ==> Configuring the HTTPS port
owncloud 10:05:53.25 INFO  ==> Configuring PHP options
owncloud 10:05:53.26 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
owncloud 10:05:53.36 INFO  ==> Restoring persisted ownCloud installation
realpath: /bitnami/owncloud/config/config.php: No such file or directory
```

I think I am doomed. Guessing this file should exist on the persistent storage, right? Which makes me wonder about the persistent storage my cloud provider (linode) provides.

I think I might be better off starting afresh.

**Comment by juan131** [comment]
Hi @brianmay 

>  finally managed to trick mariadb into resetting the passwords.

Nice! Glad to hear you could solve that.

> Guessing this file should exist on the persistent storage, right? Which makes me wonder about the persistent storage my cloud provider (linode) provides.

Correct, that file should exist, see:

```console
$ helm install owncloud bitnami/owncloud --set owncloudHost=foo.bar.com
...
$ kubectl exec $(kubectl get pods -l app.kubernetes.io/instance=owncloud,app.kubernetes.io/name=owncloud -o jsonpath='{.items[0].metadata.name}') -- ls -la /bitnami/owncloud/config
total 12
drwxr-sr-x 2 1001 1001 4096 Feb  2 14:34 .
drwxrwsr-x 5 root 1001 4096 Feb  2 14:34 ..
-rw-r----- 1 1001 1001  951 Feb  2 14:34 config.php
total 20
```

What is the version of the ownCloud chart you're trying to upgrade from? Could you please share the output of running the command below (replace the placeholder *RELEASE_NAME* with your actual release name):

```console
$ helm history RELEASE_NAME
```

**Comment by brianmay** [comment]
I am upgrading from the chart version 9.0.1 to 10.1.0. I note that there is a new version of the chart now available which I haven't tried yet.

Not sure how useful the helm upgrade history is, because I am using subcharts, and this history is truncated:

```
helm history -n owncloud owncloud
REVISION	UPDATED                 	STATUS    	CHART          	APP VERSION	DESCRIPTION     
9       	Sun Jan 31 10:54:15 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
10      	Tue Feb  2 16:33:47 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
11      	Tue Feb  2 18:53:14 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
12      	Tue Feb  2 19:42:09 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
13      	Tue Feb  2 20:02:52 2021	superseded	owncloud-0.0.0 	9.0.1      	Upgrade complete
14      	Tue Feb  2 20:09:02 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
15      	Tue Feb  2 20:10:29 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
16      	Tue Feb  2 20:21:12 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
17      	Tue Feb  2 20:24:16 2021	superseded	owncloud-10.1.0	10.1.0     	Upgrade complete
18      	Tue Feb  2 21:00:30 2021	deployed  	owncloud-10.1.0	10.1.0     	Upgrade complete
```

Unfortunately that exec command isn't going to work right now for me, because the container crashed and isn't actually running

**Comment by brianmay** [comment]
Similar to before, I kludged the container to stay alive by hacking the invocation command. "tail -f /dev/null" seems to be the best option. I think health checks might still regularly kill it, so need to be fast :-)

Looks like my persistent volume has no files other then a data directory. It looks like the same volume I had in early January too (same id).

I am at complete lose to explain what happened to my files, but I guess with no files, I might as well start afresh.

```
$ kubectl get pods -n owncloud                      
NAME                        READY   STATUS              RESTARTS   AGE
owncloud-5f5fb5c447-sxhd5   0/1     ContainerCreating   0          3m7s
owncloud-76c86b9465-zhnlc   0/1     Running             0          7m56s
owncloud-mariadb-0          1/1     Running             0          11h
$ kubectl exec -n owncloud owncloud-76c86b9465-zhnlc -- ls -la /bitnami/owncloud/config
ls: cannot access '/bitnami/owncloud/config': No such file or directory
command terminated with exit code 2
$ kubectl exec -n owncloud owncloud-76c86b9465-zhnlc -- ls -la /bitnami/owncloud/      
total 12
drwxrwsr-x 3 root 1001 4096 Feb  2 10:05 .
drwxr-xr-x 3 root root 4096 Jan  5 23:52 ..
drwxrwsr-x 2 1001 1001 4096 Feb  2 10:05 data
$ kubectl exec -n owncloud owncloud-76c86b9465-zhnlc -- ls -la /bitnami/owncloud/data
total 8
drwxrwsr-x 2 1001 1001 4096 Feb  2 10:05 .
drwxrwsr-x 3 root 1001 4096 Feb  2 10:05 ..
$ kubectl exec -n owncloud owncloud-76c86b9465-zhnlc -- mount | grep own
/dev/disk/by-id/scsi-0Linode_Volume_pvcc664b4ca65794909 on /bitnami/owncloud type ext4 (rw,relatime)
$ kubectl exec -n owncloud owncloud-76c86b9465-zhnlc -- find /bitnami/owncloud -ls
   524290      4 drwxrwsr-x   3 root     1001         4096 Feb  2 10:05 /bitnami/owncloud
   524291      4 drwxrwsr-x   2 1001     1001         4096 Feb  2 10:05 /bitnami/owncloud/data
```

**Comment by juan131** [comment]
Hi @brianmay 

There are big changes included in version `10.x` respect to prior versions. It's documented in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/owncloud#to-1000

The most important change is related to transforming ownCloud in a non-root container by default, that's also documented in the image repo, see:

- https://github.com/bitnami/bitnami-docker-owncloud#1060-debian-10-r18

As a consequence of all these changes, to migrate from `9.x` to `10.x`, you mainly have two alternatives:

- Option A (recommended):
  - (perform this step only if you have important data you don't want to lose) Make a backup of your ownCloud database and data (see https://doc.owncloud.com/server/admin_manual/maintenance/backup.html)
  - Uninstall the helm chart and remove the associated PVCs.
  - Install the chart using latest version.
  - (perform this step only if you have important data you don't want to lose)  Restore the backup in the new chart.
- Option B:
  - Upgrade the chart setting `--set containerSecurityContext.runAsUser=0,podSecurityContext.fsGroup=0` (this will basically revert the changes in the ownCloud image so it's run as a root container).

**Comment by brianmay** [comment]
Thanks for the advice. In this case however it looks like I really have no files. Not just that I can't see them due to incorrect permissions. I am going to recreate from scratch.

Closing this also, as I didn't exactly demonstrate that there were any bugs in the chart. Although I am still somewhat puzzled why the passwords were wrong.

**Comment by brianmay** [comment]
After recreating everything, it appears to be working fine. As expected.

Nervous about what will happen with the next upgrade, but hopefully I have specified the required passwords now, and there shouldn't be any issues. Fingers crossed.

**Comment by juan131** [comment]
Hi @brianmay 

Great to find out you find no issues with the new chart.

Many of the changes included in the major version **10.0.0** are intended to improve the stability of the chart so, hopefully, you shouldn't face many issues in the future. As you can see, from now on, the chart forces you to indicate the credentials (so this error won't appear again).

Our apologizes if the migration process wasn't smooth. Sometimes it's hard for us to continue improving our charts as new features of Kubernetes appear without including backwards incompatibilities. It's a balance between not breaking things, and offering an up-to-date catalog with nice features. We'll try to be more careful in the future so users like you don't face these situations. 

As a general recommendation, I encourage you to read carefully the "Upgrade" section of the README.md file whenever you upgrade between major versions of the chart. I'll personally take care of demanding clear instructions to upgrade between major versions on the PRs that attempt to bump it.

**Comment by cjohnston1158** [comment]
> No, it didn't help. Got the exact same password problem. After much work, I finally managed to trick mariadb into resetting the passwords.

@brianmay do you mind sharing how you tricked mariadb into resetting the passwords? I'm seeing this issue, and I did define a password during my initial deploy.

**Comment by brianmay** [comment]
@cjohnston1158 Knew I should have written down the steps.... I can't remember for sure, but I seem to remember I proceeded along the following steps:

1. Disable the deployment health/ready checks. I think I skipped this, but it would have helped heaps if the pod wasn't randomly killed while interacting with it.
2. Replace the pod command with a dummy command that keeps pod alive. e.g. "tail -f /dev/null" should work.
3. Start pod. Check that it is running and "healthy".
4. `kubectl exec pod -- sh` to get shell into pod.
5. Determine full command that is used to start mysql. I can't remember how I did this right now, sorry.
6. Follow instructions from https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html, but note that the full command line from step 5 is required, otherwise mysql won't find data directory.

For me this didn't work. The alter user command kept coming up with a generic error. But I think this may have been my fault, I may not have specified the hostname in the username correctly.

I think I ended up getting a mysql prompt (sorry, not sure how I did this now) and updating the table directly, using something like the instructions here: https://linuxize.com/post/how-to-reset-a-mysql-root-password/

Then undo the changes in 1 and 2, and restart the pod, and hope it works.

As I said, this still didn't give a working solution for me, but I think the mysql server was working fine.

I wish this chart had a documented procedure for resetting the root password - ideally by setting a parameter. I thought I saw a bug report on this before, but I can't find it right now.

Also see https://github.com/helm/charts/issues/217#issuecomment-505410093 - if you can set `skip-grant-tables` temporarily this might be an easier way then what I did actually. But may not be suitable if access to your mysql server is exposed to the Internet.

**Comment by juan131** [comment]
I mentioned it some posts before, I think the simplest solution is to perform a rollback. By rolling back to a previous release revision, the passwords should be set to the initial values and that should fix the issue with the credentials.

Find more info in the [Troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases)

**Comment by brianmay** [comment]
Like I mentioned above, the rollback did not help for me.
