### ISSUE TITLE
[bitnami/influxdb] timeout reached before the port went into state "inuse"

### ISSUE THREAD

**Issue by mohanagandlla** [bitnami/charts#5519]
Hi team,
I am facing this issue while the pod is getting started 
```
influxdb 04:01:07.26
influxdb 04:01:07.26 Welcome to the Bitnami influxdb container
influxdb 04:01:07.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdb
influxdb 04:01:07.27 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issues
influxdb 04:01:07.27
influxdb 04:01:07.27 INFO  ==> ** Starting InfluxDB setup **
influxdb 04:01:07.29 INFO  ==> Initializing InfluxDB...
influxdb 04:01:07.29 INFO  ==> No injected configuration files found. Creating default config files...
influxdb 04:01:07.29 INFO  ==> Deploying InfluxDB from scratch
influxdb 04:01:07.29 INFO  ==> Starting InfluxDB in background...
timeout reached before the port went into state "inuse"
influxdb 04:01:37.30 INFO  ==> Stopping InfluxDB...
```
and the influxdb version is 1.8
when i was trying to upgrade or install the new instance to 2.0 it is showing like 
my helm version is 2+

```
helm install --name influxdbtest bitnami/influxdb --set adminUser.name=admin --set adminUser.pwd=mohan --set persistence.existingClaim=pvc-influxdb --namespace  depldemo
Error: parse error in "influxdb/charts/common/templates/_secrets.tpl": template: influxdb/charts/common/templates/_secrets.tpl:84: function "lookup" not defined
```

**Comment by mohanagandlla** [comment]
sorry i found i missed the required field in the yaml deployment file DB is connecting but still getting the upgrade error as well as 
#5182

**Comment by andresbono** [comment]
Hi @mohanagandlla, thanks for opening this issue. I understand that this one is resolved and you will continue the conversations in #5182 to resolve the upgrade one, right? Let me know if not and I will reopen it. Thanks!

**Comment by jakoberpf** [comment]
Hi @mohan-nagandlla, I have the same error when deploying a vanilla fusiondb `timeout reached before the port went into state "inuse"`, but am kind clueless what the issue. You mentioned that you missed a config field. What exactly did you do to fix this? Thanks in advance.

**Comment by itobey** [comment]
For the record (even though this is a very old issue): if you happen upon this error message, check filesystem permissions for the persistent volume. This was the reason I got this error when using the Influxdb helm chart.

**Comment by uniai-sec** [comment]
I also fixed the issue by changing the read/write directory permission to `chmod 700`. I think the message should be fixed somehow.

**Comment by henrychoi7** [comment]
I also fixed the issue by changing the read/write directory permission to `chmod 700`. The error message should be guided more clearly somehow.
