### ISSUE TITLE
[bitnami/metrics-server] uses deprecated apiregistration.k8s.io/v1beta1 

### ISSUE THREAD

**Issue by philicious** [bitnami/charts#5906]
metrics-server template for apiservice needs to be adapted for latest kubernetes versions

**Which chart**:
metrics-server

**Describe the bug**
apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService

**To Reproduce**
helm diff/sync

**Comment by philicious** [comment]
@rafariossaa @andresbono while the apiVersion is fixed, there remains a cosmetical inconsistency as the metadata.name still reads v1beta1.metrics.k8s.io

(copy paste from #5909 as per request)

**Comment by alvneiayu** [comment]
hi @philicious 

The patch is already merged. Let me know if you find something else.

Thanks again for your time

**Comment by mkilchhofer** [comment]
> @rafariossaa @andresbono while the apiVersion is fixed, there remains a cosmetical inconsistency as the metadata.name still reads v1beta1.metrics.k8s.io
> 
> (copy paste from #5909 as per request)

Hi @philicious,
I think you are wrong here. Metrics still use v1beta1 API: https://github.com/kubernetes/metrics/tree/master/pkg/apis/metrics

Since PR #5968 got merged, we now have issues with metrics server. Even completely use v1 for metrics does not solve the problem:
```diff
diff --git a/bitnami/metrics-server/templates/metrics-api-service.yaml b/bitnami/metrics-server/templates/metrics-api-service.yaml
index 391fab7de..e072b5287 100644
--- a/bitnami/metrics-server/templates/metrics-api-service.yaml
+++ b/bitnami/metrics-server/templates/metrics-api-service.yaml
@@ -1,24 +1,28 @@
 {{- if .Values.apiService.create -}}
 {{- if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) }}
 apiVersion: apiregistration.k8s.io/v1beta1
 {{- else }}
 apiVersion: apiregistration.k8s.io/v1
 {{- end }}
 kind: APIService
 metadata:
 {{- if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) }}
   name: v1beta1.metrics.k8s.io
 {{- else }}
   name: v1.metrics.k8s.io
 {{- end }}
   labels: {{- include "common.labels.standard" . | nindent 4 }}
 spec:
   service:
     name: {{ template "common.names.fullname" . }}
     namespace: {{ .Release.Namespace }}
   group: metrics.k8s.io
+  {{- if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) }}
   version: v1beta1
+  {{- else }}
+  version: v1
+  {{- end }}
   insecureSkipTLSVerify: true
   groupPriorityMinimum: 100
   versionPriority: 100
 {{- end -}}
```
With this change I can deploy at least, however it does not work as expected:
```console
$ kubectl get apiservices.apiregistration.k8s.io |grep metrics
v1.metrics.k8s.io                      kube-system/metrics-server   False (FailedDiscoveryCheck)   12m
```

I think we need to revert #5968
