### ISSUE TITLE
[bitnami/mariadb-galera] configuration via ConfigMap does not work

### ISSUE THREAD

**Issue by gwvandesteeg** [bitnami/charts#7198]
**Which chart**:
[bitnami/mariabd-galera] - master branch/5.9.0

**Describe the bug**

When specifying a ConfigMap containing your configuration overrides or just editing the configuration in the chart values, the configuration does not get loaded.

**To Reproduce**

1. Change one setting in the configurations `.Values.mariadbConfiguration`, or specify your own ConfigMap via `.Values.configurationConfigMap`.  Example would be to set in the config: `max-allowed-packets=64M`.
2. Wait for the database to spin up
3. Connect to the dabatase
4. Run `SHOW VARIABLES;` and check the variable setting.  The example mentioned above would be found using. `SHOW VARIABLES where Variable_name like 'max_allowed_packet%';`
5. This will demonstrate that the configuration does not get applied correctly.

You can also see this by checking the logs of the pod post-startup
Just grep the logs for `my.cnf`, and you'll be able to find the problem.

**Expected behavior**
The specified configuration is loaded

**Version of Helm and Kubernetes**:

Not relevant, the fault is in the chart.

- Output of `helm version`:

```
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The fault is here:
https://github.com/bitnami/charts/blob/22f189d36c70da0f46733fd5da548f6ea6ec5d28/bitnami/mariadb-galera/templates/statefulset.yaml#L289

The container image is looking for its configuration file here: `/opt/bitnami/mariadb/conf/my.cnf`
The StatefulSet mounts the ConfigMap in `/bitnami/conf/my.cnf`

The config file in `/opt/bitnami/mariadb/conf/my.cnf` does an include for `/opt/bitnami/mariadb/conf/bitnami/my_custom.cnf`, but there is no further include statement to bring the ConfigMap in.

**Workaround**
Add the following to your deployment `values.yaml`
```
extraFlags: "--defaults-file '/bitnami/conf/my.cnf'"
```

**Comment by migruiz4** [comment]
Hi @gwvandesteeg,

Thank you for reporting this issue.

I have created this PR #7202 that should fix this issue.

Could you please let me know if it works for you?

**Comment by gwvandesteeg** [comment]
At the moment it "looks" right, but all attempts to upgrade the deployment of the helm chart fails with galera not synchronising with a plethora of access denied errors throughout the logs.

**Comment by gwvandesteeg** [comment]
Yeah, further investigation reveals that this does not work.  By overwriting the `my.cnf` that is in the container it is overwriting the galera node specific settings that are added during the installation or startup of the pod workers.
```
wsrep_node_name=mariadb-galera-0
wsrep_node_address=10.244.2.10
````

**Comment by migruiz4** [comment]
Reopening since the proposed fix didn't work as expected and the issue with `mariadbConfiguration` and `configurationConfigMap` persists.
More information here: https://github.com/bitnami/charts/issues/8048

**Comment by miguelaeh** [comment]
Hi @gwvandesteeg ,
I tried to reproduce the issue, but it seems to be working fine.
Where are you adding the `max_allowed_packet` ?
I edited the `values.yaml` to set `4M` and it is properly taken. Nevertheless, take into account that the configuration parameters are applied in cascade, so, the last one will be taken precedence if it is duplicated. In the case of `max_allowed_packet` it is already set in the `values.yaml` to `16M`, so if instead of editing that field you add a new one before it will never be applied.

To show how the test actually works, you can edit in the `values.yaml` the following section of the MariaDB configuration:

```
## Safety
##
skip_host_cache
skip_name_resolve
max_allowed_packet=16M
```

and after editing the `max_allowed_packet` you can execute your command inside the database to check the new value is properly set.

**Comment by miguelaeh** [comment]
Please check this: https://github.com/bitnami/charts/issues/8048#issuecomment-982861955

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by tantm3** [comment]
Hi everyone,

Is this issue solved in some PRs?
I try to increase `max_connections` config, but the values `mariadbConfiguration` and `configurationConfigMap` are not effective.
I also try using `extraFlags` and upgrade cluster with `helm upgrade` command
```
extraFlags: 
  - "--max_connections=2000"
 helm -n namespace upgrade mariadb-release -f values.yaml bitnami/mariadb-galera --set rootUser.password= --set db.password= --set galera.mariabackup.password=
```
But it shown an error:
```
2023-06-16  7:55:52 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2023-06-16  7:55:52 0 [Note] Plugin 'FEEDBACK' is disabled.
/opt/bitnami/mariadb/sbin/mysqld: Too many arguments (first extra is '[--max_connections=2000]').
2023-06-16  7:55:52 0 [ERROR] Aborting
terminate called after throwing an instance of 'wsrep::runtime_error'
  what():  State wait was interrupted
230616  7:55:52 [ERROR] mysqld got signal 6 ;
```

**Comment by migruiz4** [comment]
Hi @tantm3,

The values `extraFlags` is used to add additional flags to the mariadb command, but `max_connections` is not a valid flag.

In order to increase the setting `max_connections` of MariaDB, it has to be done in the configuration file `my.cnf`, which is set using the variables 'primary.configuration' and 'secondary.configuration', or otherwise, configuring GLOBAL as described [here](https://www.educba.com/mariadb-max-connections/).

Please keep in mind that, if you modify the value of 'primary.configuration' and/or 'secondary.configuration', you will be overriding its default value, so make sure to copy it from the chart [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml).

**Comment by tantm3** [comment]
Hi @migruiz4,

Sorry for the late response.
I tried to use the `mariadbConfiguration` configuration in the old version values file (in the attached file [values.zip](https://github.com/bitnami/charts/files/11866594/values.zip)).
But, it's not working and I think it again face with the wrong mount path:
```
# In the StatefulSet config the mountpath is `/bitnami/conf/my.cnf`
[(https://github.com/bitnami/charts/files/11866592/values.zip)

      volumeMounts:
        - name: previous-boot
          mountPath: /opt/bitnami/mariadb/.bootstrap
        - name: data
          mountPath: /bitnami/mariadb
        - name: mariadb-galera-config
          mountPath: /bitnami/conf/my.cnf
          subPath: my.cnf
# But the mariadb process read the config file in another path: /opt/bitnami/mariadb/conf/my.cnf
[values.zip](https://github.com/bitnami/charts/files/11866591/values.zip)

/opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid 
```

**Comment by romanalexander** [comment]
> Hi @migruiz4,
> 
> Sorry for the late response. I tried to use the `mariadbConfiguration` configuration in the old version values file (in the attached file [values.zip](https://github.com/bitnami/charts/files/11866594/values.zip)). But, it's not working and I think it again face with the wrong mount path:
> 
> ```
> # In the StatefulSet config the mountpath is `/bitnami/conf/my.cnf`
> [(https://github.com/bitnami/charts/files/11866592/values.zip)
> 
>       volumeMounts:
>         - name: previous-boot
>           mountPath: /opt/bitnami/mariadb/.bootstrap
>         - name: data
>           mountPath: /bitnami/mariadb
>         - name: mariadb-galera-config
>           mountPath: /bitnami/conf/my.cnf
>           subPath: my.cnf
> # But the mariadb process read the config file in another path: /opt/bitnami/mariadb/conf/my.cnf
> [values.zip](https://github.com/bitnami/charts/files/11866591/values.zip)
> 
> /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid 
> ```

This is still the case, and the issue is still ongoing. `/opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid` It will never read anything from my.cnf in `mariadbConfiguration` key

**Comment by romanalexander** [comment]
> Hi @migruiz4,
> 
> Sorry for the late response. I tried to use the `mariadbConfiguration` configuration in the old version values file (in the attached file [values.zip](https://github.com/bitnami/charts/files/11866594/values.zip)). But, it's not working and I think it again face with the wrong mount path:
> 
> ```
> # In the StatefulSet config the mountpath is `/bitnami/conf/my.cnf`
> [(https://github.com/bitnami/charts/files/11866592/values.zip)
> 
>       volumeMounts:
>         - name: previous-boot
>           mountPath: /opt/bitnami/mariadb/.bootstrap
>         - name: data
>           mountPath: /bitnami/mariadb
>         - name: mariadb-galera-config
>           mountPath: /bitnami/conf/my.cnf
>           subPath: my.cnf
> # But the mariadb process read the config file in another path: /opt/bitnami/mariadb/conf/my.cnf
> [values.zip](https://github.com/bitnami/charts/files/11866591/values.zip)
> 
> /opt/bitnami/mariadb/sbin/mysqld --defaults-file=/opt/bitnami/mariadb/conf/my.cnf --basedir=/opt/bitnami/mariadb --datadir=/bitnami/mariadb/data --socket=/opt/bitnami/mariadb/tmp/mysql.sock --pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid 
> ```

Hey, for any time travelers in the future seeing this, be careful which values you edit in the my.cnf, some variables like [the ones here](https://github.com/bitnami/containers/blob/d18b9891721c5b11b9bed1aaf678da336896908c/bitnami/mariadb-galera/11.4/debian-12/rootfs/opt/bitnami/scripts/mariadb-env.sh#L26-L81) are controlled through an undocumented environment variable you must hunt down. namely slow_query_log and long_query_time
