### ISSUE TITLE
Argo 3.3.1 workflow user "system:serviceaccount:..." cannot list resource "secrets" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by mikulass** [bitnami/charts#9692]
### Name and Version

bitnami/argo-workflows 1.1.8

### What steps will reproduce the bug?

Hello apologize if this is wrong place to ask... I've deployed argo-workflows 3.3.1 with bitnami helm chart on k8s (into ns argo-events). 

After chart deployment I see following warning/error message in controller log:
W0405 18:04:56.432746       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1alpha1.WorkflowTaskResult: [workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/) is forbidden: User "system:serviceaccount:argo-events:argo-iwcp-01-argo-workflows-controller" cannot list resource "workflowtaskresults" in API group "[argoproj.io](http://argoproj.io/)" at the cluster scope

E0405 18:04:56.432772       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: [workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/) is forbidden: User "system:serviceaccount:argo-events:argo-iwcp-01-argo-workflows-controller" cannot list resource "workflowtaskresults" in API group "[argoproj.io](http://argoproj.io/)" at the cluster scope...

Before this version I was running 3.2.7 without any warning/error.. 

Any Idea how to fix this?

Thanks.

### Are you using any custom parameters or values?

I'm using values from https://github.com/bitnami/charts/blob/master/bitnami/argo-workflows/values.yaml with default parameters for serviceAccount

With sso enabled I was not able to start argo-workflows 3.3.1 (it worked without issue on 3.2.7..), than I've changed to client and it started but the issue : cannot list resource "secrets" in API group "" at the cluster scope persisted..

### What do you see instead?

E0405 18:04:56.432772       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: [workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/) is forbidden: User "system:serviceaccount:argo-events:argo-iwcp-01-argo-workflows-controller" cannot list resource "workflowtaskresults" in API group "[argoproj.io](http://argoproj.io/)" at the cluster scope...

**Comment by dgomezleon** [comment]
Hi @mikulass ,

I have merged a PR to fix the problem. Please let us know if you find any other issues.

**Comment by mikulass** [comment]
Hello @dgomezleon,
many thanks for PR to fix the problem. I've just deployed :

CHART NAME: argo-workflows
CHART VERSION: 1.1.4
APP VERSION: 3.3.1

with updated values.yaml, but I still see same error in **controller** pod: 

time="2022-04-06T20:34:39.433Z" level=info msg="Update leases 200"
time="2022-04-06T20:34:40.391Z" level=info msg="List workflowtaskresults 403"
W0406 20:34:40.391993       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1alpha1.WorkflowTaskResult: workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:argo-events:argo-iwcp-01-argo-workflows-controller" cannot list resource "workflowtaskresults" in API group "argoproj.io" at the cluster scope
E0406 20:34:40.392026       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskResult: failed to list *v1alpha1.WorkflowTaskResult: workflowtaskresults.argoproj.io is forbidden: User "system:serviceaccount:argo-events:argo-iwcp-01-argo-workflows-controller" cannot list resource "workflowtaskresults" in API group "argoproj.io" at the cluster scope
time="2022-04-06T20:34:44.450Z" level=info msg="Get leases 200"

and I can't to log in GUI..

Thanks. Regards. Mikulas.

**Comment by dgomezleon** [comment]
Hi @mikulass ,

Sorry for the delay due to Holy Week. We are working on reproducing the issue and will let you know any advance.

Regards

**Comment by dgomezleon** [comment]
Hi @mikulass, 

I was not able to reproduce the issue. Anyway I would try to add the action `list` in `templates/server/cluster-role.yaml`:

```diff
  {{- if and .Values.server.auth.enabled .Values.server.auth.sso.enabled }}
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - sso
    verbs:
      - get
      - update
+     - list
```

Another valid verbs are `watch`, `create`, `delete`, and `patch`. Ideally, we should only add the necessary ones to make it work.

Could you try that?

**Comment by ktaletsk** [comment]
Hi @dgomezleon,

Thanks for recommendation here:
> Anyway I would try to add the action `list` in `templates/server/cluster-role.yaml`:
> 
> ```diff
>   {{- if and .Values.server.auth.enabled .Values.server.auth.sso.enabled }}
>   - apiGroups:
>       - ""
>     resources:
>       - secrets
>     resourceNames:
>       - sso
>     verbs:
>       - get
>       - update
> +     - list
> ```
> 
> Another valid verbs are `watch`, `create`, `delete`, and `patch`. Ideally, we should only add the necessary ones to make it work.
> 
> Could you try that?

I tried it and it did not fix the SSO. It looks like `list` needs to be added to a different block in the clusterrole file, which fixes the issue.

```diff
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
+     - list
```

PR with the fix to follow

**Comment by dgomezleon** [comment]
Hi @ktaletsk ,

Thanks for contributing. We will check your PR. What you say makes sense after checking the [upstream values](https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/templates/server/server-cluster-roles.yaml).
